src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracking checkbox for clients of TriTech, any division</description>
        <label>Client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
                <value>
                    <fullName>IMC</fullName>
                    <color>#78C953</color>
                    <label>IMC</label>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                    <color>#F3D904</color>
                    <label>VisiNet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>IQ</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestAvailableDownloadsController.cls
/*********************************************************************************
* Test Class: {TestAvailableDownloadsController}
* Created by {Madan Vishwakarma}, Navivo, {DateCreated 09/17/2014}
----------------------------------------------------------------------------------
* Purpose/Methods:
* - {Increasing Code coverage of AvailableDownloadsController.cls}
----------------------------------------------------------------------------------
* Utility Test Data: {}
----------------------------------------------------------------------------------
* History:
* - VERSION DEVELOPER NAME DATE DETAIL FEATURES
1.0 Madan 09/17/2014 INITIAL DEVELOPMENT
2.0 Name MM/DD/YYYY UDAC WIRE FRAME CHANGES*/

@isTest
private class TestAvailableDownloadsController {

    static testMethod void myUnitTest() {
        
        
        ContentVersion cv = new contentVersion();
        cv.VersionData = Blob.valueOf('test');
        cv.Title = 'testMV';
        cv.Description = 'test';
        //cv.FirstPublishLocationId = [Select Id From ContentWorkspace c where (Name = 'Perform' OR Name = 'EMS' OR Name = 'Zuercher')].Id;
        cv.PathOnClient = '/test.txt';
        insert cv;
        
        //ContentWorkspace contWorkspace = new ContentWorkspace();
        //insert contWorkspace;
        
        AvailableDownloadsController avlDownloadObj = new AvailableDownloadsController();
        List<AvailableDownloadsController.AvailableDownload> lstAvlDownload = avlDownloadObj.getAvailableDownloads();
        
        AvailableDownloadsController.AvailableDownload avlDown = new AvailableDownloadsController.AvailableDownload();
        
        avlDown.description = 'test';
    }/*
    static testMethod void myUnitTest1() {
        Test.startTest();
        Profile portalProfile = [ select Id from Profile where Name = 'TriTech Portal Manager' Limit 1];
        
        Account a = new Account();
        a.Name = 'Test Account';
        a.Client__c = true;
        insert a;
            
        Contact c = new Contact();
        c.AccountId = a.Id;
        c.LastName = 'Test cont';
        c.MailingStreet = 'street';
        c.MailingCity = 'city';
        c.MailingState = 'state';
        c.MailingPostalCode = '12345';
        c.MailingCountry = 'us';
        insert c;
        String str = System.now().getTime().intValue().format();
        str = str.replaceAll(',', '');
        User u2 = new User();
        u2.Email = 'testBatchIdeasReport' + str + '@test.com';
        u2.Alias = 'prts';
        u2.TimeZoneSidKey = 'America/New_York';
        u2.LocaleSidKey = 'ca';
        u2.EmailEncodingKey = 'UTF-8';
        u2.ProfileId = portalProfile.Id;
        u2.LanguageLocaleKey = 'en_US';
        u2.FirstName = 'testFN';
        u2.LastName = 'testLN';
        u2.PortalRole = 'Test Account Customer Manager';
        u2.username= 'testBatchIdeasReport' + str + '@test.com';
        u2.ContactId = c.Id;
        u2.CompanyName = 'Test Company';
        insert u2;
        
        
        
        ContentVersion cv = new contentVersion();
        cv.VersionData = Blob.valueOf('test');
        cv.Title = 'testMV';
        cv.Description = 'test';
        cv.FirstPublishLocationId = [Select Id From ContentWorkspace c where (Name = 'Perform' OR Name = 'EMS')].Id;
        cv.PathOnClient = '/test.txt';
        insert cv;
        
        System.runAs(u2) {
            List<ServiceContract> scList = new List<ServiceContract>();
            ServiceContract sc1 = new ServiceContract(Name = 'SC1',Contract_Type__c = 'EMS', Contract_Status_WMP__c = 'Active', AccountId = a.Id);
            scList.add(sc1);
            ServiceContract sc2 = new ServiceContract(Name = 'SC2',Product_Family_WMP__c = 'VisiNet',Contract_Status_WMP__c = 'Active', AccountId = a.Id);
            scList.add(sc2);
            ServiceContract sc3 = new ServiceContract(Name = 'SC3',Product_Family_WMP__c = 'IMC',Contract_Status_WMP__c = 'Active', AccountId = a.Id);
            scList.add(sc3);
            insert scList;
            AvailableDownloadsController avlDownloadObj = new AvailableDownloadsController();
            List<AvailableDownloadsController.AvailableDownload> lstAvlDownload = avlDownloadObj.getAvailableDownloads();
            
            AvailableDownloadsController.AvailableDownload avlDown = new AvailableDownloadsController.AvailableDownload();
            PortalUserUtil.ProductFamilies p = new PortalUserUtil.ProductFamilies();
            p.productFamilyIMC = true;
            avlDown.description = 'test';
        }Test.stopTest();
    }
    static testMethod void myUnitTest2() {
        Test.startTest();
        Profile portalProfile = [ select Id from Profile where Name = 'TriTech Portal Manager' Limit 1];
        Account a = new Account();
        a.Name = 'Test Account';
        a.Client__c = true;
        insert a;
            
        Contact c = new Contact();
        c.AccountId = a.Id;
        c.LastName = 'Test cont';
        c.MailingStreet = 'street';
        c.MailingCity = 'city';
        c.MailingState = 'state';
        c.MailingPostalCode = '12345';
        c.MailingCountry = 'us';
        insert c;
        String str = System.now().getTime().intValue().format();
        str = str.replaceAll(',', '');
        User u2 = new User();
        u2.Email = 'testBatchIdeasReport' + str + '@test.com';
        u2.Alias = 'prts';
        u2.TimeZoneSidKey = 'America/New_York';
        u2.LocaleSidKey = 'ca';
        u2.EmailEncodingKey = 'UTF-8';
        u2.ProfileId = portalProfile.Id;
        u2.LanguageLocaleKey = 'en_US';
        u2.FirstName = 'testFN';
        u2.LastName = 'testLN';
        u2.username= 'testBatchIdeasReport' + str + '@test.com';
        u2.ContactId = c.Id;
        u2.PortalRole = 'Test Account Customer Manager';
        u2.CompanyName = 'Test Company';
        insert u2;
        System.runAs(u2) {
            List<ServiceContract> scList = new List<ServiceContract>();
            ServiceContract sc1 = new ServiceContract(Name = 'SC1',Contract_Type__c = 'EMS',Product_Family_WMP__c = 'EMS', Contract_Status_WMP__c = 'Active', AccountId = a.Id);
            scList.add(sc1);
            ServiceContract sc2 = new ServiceContract(Name = 'SC2',Product_Family_WMP__c = 'VisiNet',Contract_Status_WMP__c = 'Active', AccountId = a.Id);
            scList.add(sc2);
            ServiceContract sc3 = new ServiceContract(Name = 'SC3',Product_Family_WMP__c = 'IMC',Contract_Status_WMP__c = 'Active', AccountId = a.Id);
            scList.add(sc3);
            insert scList;
            AvailableDownloadsController avlDownloadObj = new AvailableDownloadsController();
            List<AvailableDownloadsController.AvailableDownload> lstAvlDownload = avlDownloadObj.getAvailableDownloads();
            
            AvailableDownloadsController.AvailableDownload avlDown = new AvailableDownloadsController.AvailableDownload();
            PortalUserUtil.ProductFamilies p = new PortalUserUtil.ProductFamilies();
            p.productFamilyEMS = true;
            avlDown.description = 'test';
        }Test.stopTest();
    }*/
        
}