src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Yearly_Contact_Customer_Risk_Level__c</fullName>
        <label>xLast Yearly Contact Customer Risk Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Z_Completed_Yearly_Contacts__c</fullName>
        <label>Completed Yearly Wellness Checks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Z_Last_Yearly_Contact_Date__c</fullName>
        <label>Last Wellness Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Z_Last_Yearly_Contact_Type__c</fullName>
        <label>Last Wellness Check Type</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClientContactTaskTest.cls
@isTest
private class ClientContactTaskTest {
        static testMethod void ClientContactTask() {
         Account acct = new Account();
         acct.name = 'Test Acct';
         acct.Z_Completed_Yearly_Contacts__c = 1;
         acct.Z_Last_Yearly_Contact_Date__c = System.Today() - 30;
         acct.Z_Last_Yearly_Contact_Type__c = 'Call';
         acct.Last_Yearly_Contact_Customer_Risk_Level__c = 'Low';
         insert acct;
         
         Event evt = new Event();
         evt.WhatId = acct.id;
         evt.Z_Logged_Client_Relations_Contact__c = true;
         evt.ActivityDateTime = System.Now();
       
         evt.Type = 'Client Relations - Call';
         evt.DurationInMinutes = 120;
         insert evt;
         evt.DurationInMinutes = 100;
         upsert evt;
         
         Task tsk = new Task();
         tsk.WhatId = acct.id;
         tsk.Type = 'Client Relations - Call';
         tsk.ActivityDate = System.today() - 10;
         tsk.Customer_Risk_Level__c = 'Low';
         tsk.Z_Logged_Client_Relations_Contact__c = true;
		 insert tsk;
		 tsk.Customer_Risk_Level__c = 'High';
		 upsert tsk;
		 
		 tsk.ActivityDate = System.today();
         upsert tsk;
		 evt.ActivityDateTime = System.Now() - 10;
         upsert evt;
         
         
		 
        }

    }