src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product_Family2__c</fullName>
        <formula>IF(INCLUDES(Account.Product_Family_WMP__c, &quot;EMS&quot;), &apos;EMS;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;IMC&quot;), &apos;IMC;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;Inform&quot;), &apos;Inform;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;VisiNet&quot;), &apos;VisiNet;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;VisionAIR&quot;), &apos;VisionAIR;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;Tiburon&quot;), &apos;Tiburon;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;911&quot;), &apos;911;&apos;,&apos;&apos;) +
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;Zuercher&quot;), &apos;Zuercher;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;ZSuite&quot;), &apos;ZSuite;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;LETG&quot;), &apos;LETG;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;Insight&quot;), &apos;Insight;&apos;,&apos;&apos;) + 
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;GIS&quot;), &apos;GIS;&apos;,&apos;&apos;) +
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;Omega&quot;), &apos;Omega;&apos;,&apos;&apos;) +
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;ETI&quot;), &apos;ETI;&apos;,&apos;&apos;) +
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;ETI 911&quot;), &apos;ETI 911;&apos;,&apos;&apos;) +
IF(INCLUDES(Account.Product_Family_WMP__c, &quot;Impact&quot;), &apos;Impact;&apos;,&apos;&apos;)</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Contract</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Contract Amendment</fullName>
                </value>
                <value>
                    <fullName>Sales Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
                <value>
                    <fullName>IMC</fullName>
                    <color>#78C953</color>
                    <label>IMC</label>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                    <color>#F3D904</color>
                    <label>VisiNet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Derived_Prd_Family_from_Contract_Type__c</fullName>
        <description>This field is used to map the product family to the contract type and allows for filtering in the Knowledge base.  This field should never be on the contract page layout.</description>
        <formula>IF( ISPICKVAL( Contract_Type__c , &quot;Billing&quot;) , &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;EMS CAD&quot;) , &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;FDC&quot;), &quot;EMS&quot;, 
 IF( ISPICKVAL( Contract_Type__c , &quot;Fusion ePCR&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;Fusion Online&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;IMC&quot;), &quot;IMC&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;SBS&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;Sweet-Online&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;VisiNet&quot;), &quot;VisiNet&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;AVeL&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;VisionAIR&quot;), &quot;VisionAIR&quot;,
&quot;Unknown&quot;
)))))))))))</formula>
        <label>Derived Prd Family from Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>IQ</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PortalUserUtil.cls
public without sharing class PortalUserUtil {
  //Mohan 8.11.2015 - Inform contract should show the visinet filter
  public static final String INFORM_PRODUCT_FAMILY = 'Inform';
  public static final String RESPOND_PRODUCT_FAMILY = 'Respond';
    
  public static final String IMC_PRODUCT_FAMILY = 'IMC';
  
  public static final String PERFORM_PRODUCT_FAMILY = 'Perform';

  public static final String EMS_PRODUCT_FAMILY = 'EMS';

  public static final String VISINET_PRODUCT_FAMILY = 'VisiNet';

  public static final String VISIONAIR_PRODUCT_FAMILY = 'VisionAIR';
  
  public static final String PRODUCT_FAMILY_911 = '911';
  
  //12-11-2015 - add the Tiburon data category and subcategory filters
  public static final String PRODUCT_FAMILY_Tiburon = 'Tiburon';
  
  public static final String PRODUCT_FAMILY_Zuercher = 'Zuercher';
  public static final String PRODUCT_FAMILY_LETG = 'LETG';
  
  public static final String PRODUCT_FAMILY_ETI = 'ETI';
  public static final String PRODUCT_FAMILY_ETI911 = 'ETI 911';
    
    /*
    * Get the product families based on the account associated with the profile user's contact
    */
    public static ProductFamilies getProductFamilies(String portalUserId) {
        Account acct = null;
        PortalUserUtil.ProductFamilies prodFamilies = new ProductFamilies();
        
    system.debug('getProductFamilies: portalUserId [' + portalUserId + ']');

      User portalUser = [SELECT ContactId FROM User WHERE Id = :portalUserId];
      system.debug('getProductFamilies: portalUser contact [' + portalUser.ContactId + ']');
      

      if (portalUser.ContactId != null) {
        //Contact cnct = [SELECT AccountID FROM Contact WHERE Id = :portalUser.ContactId];
        Contact cnct = [SELECT Product_Family2__c FROM Contact WHERE Id = :portalUser.ContactId];
        
        if ((cnct != null) && (cnct.Product_Family2__c != null)) {
          system.debug('getProductFamilies: Contact Product_Family2__c [' + cnct.Product_Family2__c + ']');
          prodFamilies.productFamilyIMC = cnct.Product_Family2__c.contains(IMC_PRODUCT_FAMILY);
          prodFamilies.productFamilyEMS = cnct.Product_Family2__c.contains(EMS_PRODUCT_FAMILY);
          prodFamilies.productFamilyVisiNet = cnct.Product_Family2__c.contains(VISINET_PRODUCT_FAMILY);
          prodFamilies.productFamilyVisionAIR = cnct.Product_Family2__c.contains(VISIONAIR_PRODUCT_FAMILY);
          prodFamilies.productFamily911 = cnct.Product_Family2__c.contains(PRODUCT_FAMILY_911);
          prodFamilies.productFamilyTiburon = cnct.Product_Family2__c.contains(PRODUCT_FAMILY_Tiburon);
          prodFamilies.productFamilyZuercher = cnct.Product_Family2__c.contains(PRODUCT_FAMILY_Zuercher);
          prodFamilies.productFamilyLETG = cnct.Product_Family2__c.contains(PRODUCT_FAMILY_LETG);
          //prodFamilies.productFamily911 = cnct.Product_Family2__c.contains(PRODUCT_FAMILY_ETI);
          //prodFamilies.productFamily911 = cnct.Product_Family2__c.contains(PRODUCT_FAMILY_ETI911);
        }

        /*
        if (cnct.AccountId != null) {
            
            //Get the Account this contact is associated with as that has the definitive product family value
            List<Account> accounts = [SELECT Product_Family_WMP__c FROM Account WHERE Id = :cnct.AccountID];
            if (accounts.size() > 0) {
                acct = accounts.get(0);
            }
            
            if ((acct != null) && (acct.Product_Family_WMP__c != null)) {
                system.debug('getProductFamilies: Account Product_Family_WMP__c [' + acct.Product_Family_WMP__c + ']');
              prodFamilies.productFamilyIMC = acct.Product_Family_WMP__c.contains(IMC_PRODUCT_FAMILY);
              prodFamilies.productFamilyEMS = acct.Product_Family_WMP__c.contains(EMS_PRODUCT_FAMILY);
              prodFamilies.productFamilyVisiNet = acct.Product_Family_WMP__c.contains(VISINET_PRODUCT_FAMILY);
              prodFamilies.productFamilyVisionAIR = acct.Product_Family_WMP__c.contains(VISIONAIR_PRODUCT_FAMILY);
            }
          }
          */
      }
        
        return prodFamilies;
    }
  
 /*
  * Get the product families based on the active contracts associated with the profile user's contact/account
  */
  public static ProductFamilies getProductFamiliesByContract(String portalUserId) {
    Account acct = null;
    PortalUserUtil.ProductFamilies prodFamilies = new ProductFamilies();
    
    system.debug('getProductFamiliesByContract: portalUserId [' + portalUserId + ']');

      User portalUser = [SELECT ContactId FROM User WHERE Id = :portalUserId];
      system.debug('getProductFamiliesByContract: portalUser contact [' + portalUser.ContactId + ']');
      
      if (portalUser.ContactId != null) {
        //Contact cnct = [SELECT AccountID FROM Contact WHERE Id = :portalUser.ContactId];
        Contact cnct = [SELECT AccountId FROM Contact WHERE Id = :portalUser.ContactId];
        
        if (cnct.AccountId != null) {
          
          //Get the Account this contact is associated with as that has the definitive product family value
          List<Account> accounts = [SELECT Id FROM Account WHERE Id = :cnct.AccountID];
          if (accounts.size() > 0) {
            acct = accounts.get(0);
          }
          
          if (acct != null) {
            system.debug('getProductFamiliesByContract: Account Id [' + acct.Id + ']');
            
            //set the "active" contract types to everything but inactive or suspended
            Set<String> activeContractValues = new Set<String>();
            activeContractValues.add('Active');
            activeContractValues.add('Installed Not Live');     //Mohan 10-04-2014: Installed Not Live is considered as Active status
            activeContractValues.add('Renewal Due');
            activeContractValues.add('No HW Support, Software Only');
            //activeContractValues.add('Emergency Support Only');
            //activeContractValues.add('Installed Not Live');
            //activeContractValues.add('Sold but Not Installed');
            //activeContractValues.add('Vendor/Partner');
            
            //get the active contracts for this account
            List<ServiceContract> activeContracts = [SELECT Id, Contract_Type__c, Product_Family_WMP__c, Derived_Prd_Family_from_Contract_Type__c FROM ServiceContract WHERE AccountId = :acct.Id AND Contract_Status_WMP__c IN :activeContractValues];
            
            //set the available product families based on the values on the contract
            List<String> activeContractTypes = new List<String>();
            for (ServiceContract contract : activeContracts) {
                activeContractTypes.add(contract.Contract_Type__c);
                 
              if (IMC_PRODUCT_FAMILY == contract.Product_Family_WMP__c || PERFORM_PRODUCT_FAMILY == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyIMC = true;
              } else if (EMS_PRODUCT_FAMILY == contract.Product_Family_WMP__c || RESPOND_PRODUCT_FAMILY == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyEMS = true;
              } else if (VISINET_PRODUCT_FAMILY == contract.Product_Family_WMP__c || INFORM_PRODUCT_FAMILY == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyVisiNet = true;
              } else if (VISIONAIR_PRODUCT_FAMILY == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyVisionAIR = true;
              } else if(PRODUCT_FAMILY_911 == contract.Product_Family_WMP__c) {
                prodFamilies.productFamily911 = true;
              } else if(PRODUCT_FAMILY_Tiburon == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyTiburon = true;
              } else if(PRODUCT_FAMILY_Zuercher == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyZuercher = true;
              } else if(PRODUCT_FAMILY_LETG == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyLETG = true;
              } else if(PRODUCT_FAMILY_ETI == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyETI = true;
              } else if(PRODUCT_FAMILY_ETI911 == contract.Product_Family_WMP__c) {
                prodFamilies.productFamilyETI911 = true;
              }
            }
            
            prodFamilies.activeContractTypes = activeContractTypes;
            
             
          }
        }
        
      }
    
    return prodFamilies;
  }

  public class ProductFamilies {
    public boolean productFamilyIMC {get;set;}
    public boolean productFamilyEMS {get;set;}
    public boolean productFamilyVisiNet {get;set;}
    public boolean productFamilyVisionAIR {get;set;}
    public boolean productFamily911 {get;set;}
    public boolean productFamilyTiburon {get;set;}
    public boolean productFamilyZuercher {get;set;}
    public boolean productFamilyLETG {get;set;}
    public boolean productFamilyETI {get;set;}
    public boolean productFamilyETI911 {get;set;}
    public List<String> activeContractTypes {get;set;}
    
    public ProductFamilies() {
        
    }
  }
  
  static testmethod void testProductFamiliesByContract() {
    User usr = [SELECT Id FROM User WHERE IsActive = true AND ContactId != NULL LIMIT 1];
    PortalUserUtil.getProductFamiliesByContract(usr.Id);
    
  }
  
  static testmethod void testProductFamiliesByContract2() {
    User usr = [SELECT Id FROM User WHERE IsActive = true AND ContactId != NULL LIMIT 1];
    PortalUserUtil.getProductFamilies(usr.Id);
    
  }
}