src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KB_Search_Result__c.object
<CustomObject>
    <fields>
        <fullName>Article_Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>KB_Search_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Article_ID__c</fullName>
        <label>Article ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Published_Date__c</fullName>
        <label>Article Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Defect</fullName>
                </value>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>How To</fullName>
                </value>
                <value>
                    <fullName>Release Notes</fullName>
                </value>
                <value>
                    <fullName>Tech Advisory</fullName>
                </value>
                <value>
                    <fullName>Tech Tips</fullName>
                </value>
                <value>
                    <fullName>Ticket Solutions</fullName>
                </value>
                <value>
                    <fullName>User Manuals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Article_Viewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Article Viewed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Product Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>911-Inc</fullName>
                </value>
                <value>
                    <fullName>Perform</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KB_Search_Tracking__c</fullName>
        <label>KB Search Tracking</label>
        <referenceTo>KB_Search_Tracking__c</referenceTo>
        <relationshipLabel>KB Search Result</relationshipLabel>
        <relationshipName>KB_Search_Result</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>KB Search Result</label>
    <nameField>
        <displayFormat>KBSR-{0000}</displayFormat>
        <label>KB Search Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KB Search Result</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KB_Search_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal App</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Public Knowledge Base</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Product_Family__c</fullName>
        <label>Customer Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMS_Filter__c</fullName>
        <label>EMS Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IMC_Filter__c</fullName>
        <label>IMC Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keyword__c</fullName>
        <label>Keyword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Date__c</fullName>
        <label>Search Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Search_In_Article_Types__c</fullName>
        <label>Search In Article Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Defect</fullName>
                </value>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>How To</fullName>
                </value>
                <value>
                    <fullName>Release Notes</fullName>
                </value>
                <value>
                    <fullName>Tech Advisory</fullName>
                </value>
                <value>
                    <fullName>Tech Tips</fullName>
                </value>
                <value>
                    <fullName>Ticket Solutions</fullName>
                </value>
                <value>
                    <fullName>User Manuals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Search_Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Search Success?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>KB_Search_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisiNet_Filter__c</fullName>
        <label>VisiNet Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisionAIR_Filter__c</fullName>
        <label>VisionAIR Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KB Search Tracking</label>
    <nameField>
        <displayFormat>KBST-{0000}</displayFormat>
        <label>KB Search Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KB Search Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KBUtility.cls
/*********************************************************************************
* Test Class: {KBUtility}
* Created by {Madan Vishwakarma}, Navivo, {DateCreated 08/26/2014}
----------------------------------------------------------------------------------
* Purpose/Methods:
* - {This utility class are created to provide all tooles which are helpfull in KB report generation.}
----------------------------------------------------------------------------------
* Utility Test Data: {}
----------------------------------------------------------------------------------
* History:
* - VERSION DEVELOPER NAME DATE DETAIL FEATURES
1.0 Madan 08/26/2014 INITIAL DEVELOPMENT
2.0 Name MM/DD/YYYY UDAC WIRE FRAME CHANGES
*********************************************************************************/

public with sharing class KBUtility {
	
	//save all data which are used to filter search result
	public static String saveSearchTracking(String keyword, Boolean isSuccess, String emsFilter, String imcFilter, String visiNetFilter, String visionAIRFilter, Boolean defectSearch, Boolean howtoSearch, Boolean techAdvisorySearch, Boolean ticketSolutionsSearch, Boolean faqSearch, Boolean releaseNotesSearch, Boolean techTipsSearch, Boolean userManualsSearch, Boolean videoSearch){
		try{
			KB_Search_Tracking__c kbSearchTracking = new KB_Search_Tracking__c();
			kbSearchTracking.Keyword__c = keyword;
			kbSearchTracking.Search_Date__c = datetime.now();
			kbSearchTracking.Search_Success__c = isSuccess;
			kbSearchTracking.EMS_Filter__c = emsFilter;
			kbSearchTracking.IMC_Filter__c = imcFilter;
			kbSearchTracking.VisiNet_Filter__c = visiNetFilter;
			kbSearchTracking.VisionAIR_Filter__c = visionAIRFilter;
			kbSearchTracking.Channel__c = '';
			kbSearchTracking.User__c = Userinfo.getUserId();
			
			for(User u : [Select Id,Contact.Account.Product_Family_WMP__c From User Where Id = : kbSearchTracking.User__c AND Contact.Account.Product_Family_WMP__c != null Limit 1]){
				kbSearchTracking.Customer_Product_Family__c = u.Contact.Account.Product_Family_WMP__c;
			}
			
			//------------------------------------------------------------------------
			String articleTypes = '';
			
			if(defectSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; Defect';
				else articleTypes += 'Defect';
			}
			if(howtoSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; How To';
				else articleTypes += 'How To';
			}
			if(techAdvisorySearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; Tech Advisory';
				else articleTypes += 'Tech Advisory';
			}
			if(ticketSolutionsSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; Ticket Solutions';
				else articleTypes += 'Ticket Solutions';
			}
			if(videoSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; Video';
				else articleTypes += 'Video';
			}
			if(faqSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; FAQ';
				else articleTypes += 'FAQ';
			}
			if(releaseNotesSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; Release Notes';
				else articleTypes += 'Release Notes';
			}
			if(techTipsSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; Tech Tips';
				else articleTypes += 'Tech Tips';
			}
			if(userManualsSearch){
				if(articleTypes != '' && articleTypes != null) articleTypes += '; User Manuals';
				else articleTypes += 'User Manuals';
			}
			
			kbSearchTracking.Search_In_Article_Types__c = articleTypes;
			
			//--------------------------------------------------------------------
			for(User u : [Select id, ContactId, UserType from User where id =: Userinfo.getUserId()]){
				if(u.ContactId != null && u.UserType == 'PowerPartner') kbSearchTracking.Channel__c = 'Partner';
				else if(u.ContactId != null) kbSearchTracking.Channel__c = 'Customer';
				else kbSearchTracking.Channel__c = 'Internal App';
			}
			
			//Insert Search Article Details
			insert kbSearchTracking;
			return kbSearchTracking.Id;
		}
		catch(Exception ex){
			return null;
		}
	}
	
	//Save serach results.
	public static void saveSearchResult(String searchTrackingId, List<ArticleWrapper> lstSearchResult){
		try{
			if(lstSearchResult.size() > 0 && searchTrackingId != null){
				List<KB_Search_Result__c> lstKBSearchResult = new List<KB_Search_Result__c>();
				KB_Search_Result__c kbSearchResultRecord;
				for(ArticleWrapper record:lstSearchResult){
					kbSearchResultRecord = new KB_Search_Result__c();
					
					kbSearchResultRecord.Article_ID__c = record.articleId;
					kbSearchResultRecord.Article_Published_Date__c = record.articlePublishDate;
					kbSearchResultRecord.Article_Title__c = record.articleTitle;
					kbSearchResultRecord.Article_Type__c = record.articleType;
					kbSearchResultRecord.Article_Author__c = record.createdById;
					kbSearchResultRecord.Category_Group__c = record.categoryGroups;
					kbSearchResultRecord.KB_Search_Tracking__c = searchTrackingId;
					
					lstKBSearchResult.add(kbSearchResultRecord);
				}
				if(lstKBSearchResult.size() > 0) insert lstKBSearchResult;
			}	
		}
		catch(Exception ex){
			//add message here
		}
	}
	
	//Update filed when customer click any search article.
	public static void updateArticleViewed(String articleId, String searchTrackingId){
		try{
			List<KB_Search_Result__c> lstUpdateSearchResult = new List<KB_Search_Result__c>();
			for(KB_Search_Result__c sResult : [select id, Article_Viewed__c from KB_Search_Result__c where Article_ID__c =: articleId and KB_Search_Tracking__c =: searchTrackingId]){
				sResult.Article_Viewed__c = true;
				lstUpdateSearchResult.add(sResult);
			}
			if(lstUpdateSearchResult.size() > 0) update lstUpdateSearchResult;
		}
		catch(Exception ex){
			//add message here
		}
	}
	
	public static Integer keywordMatched(String searchWords, String artTitle) {
		Integer matchCount = 0;
		searchWords = searchWords.toLowerCase();
		artTitle = (artTitle != null ? artTitle.toLowerCase() : '');
		for(String s: searchWords.split(' ')) {
			if(artTitle.contains(s)) {
				matchCount++;
			}
		}
		return matchCount;
	}
}