src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Number_of_Sworn_Personnel_WMP__c</fullName>
        <description>Field is currently locked down to read only to all users except for sys admins and users with the &quot;Account_Sworn Counts and Hierarchy Changes&quot; permission set associated to their user record.</description>
        <label>Number of Sworn Officers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMS_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Utilized to indicate the Agency&apos;s RMS Parent Account</inlineHelpText>
        <label>RMS Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X911_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Utilized to indicate the Agency&apos;s 911 Parent Account</inlineHelpText>
        <label>911 Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (911 Parent Account)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestUpdateRollUpFieldOnAccount.cls
@isTest
private class TestUpdateRollUpFieldOnAccount {
    static testMethod void testParentId() {
        //Create Account
        Account acc = new Account();
        acc.Name = 'test';
        acc.Number_of_Sworn_Personnel_WMP__c = 5;
        
        insert acc;
        
        Account accLevel1 = new Account();
        accLevel1.Name = 'test';
        accLevel1.Number_of_Sworn_Personnel_WMP__c = 4;
        accLevel1.ParentId = acc.id;
        
        insert accLevel1;
    }
    
    static testMethod void test911ParentId() {
        //Create Account
        Account acc = new Account();
        acc.Name = 'test';
        acc.Number_of_Sworn_Personnel_WMP__c = 5;
        
        insert acc;
        
        Account accLevel1 = new Account();
        accLevel1.Name = 'test';
        accLevel1.Number_of_Sworn_Personnel_WMP__c = 4;
        accLevel1.X911_Parent_Account__c = acc.id;
        
        insert accLevel1;
    }
    
    static testMethod void testRMSParentId() {
        //Create Account
        Account acc = new Account();
        acc.Name = 'test';
        acc.Number_of_Sworn_Personnel_WMP__c = 5;
        
        insert acc;
        
        Account accLevel1 = new Account();
        accLevel1.Name = 'test';
        accLevel1.Number_of_Sworn_Personnel_WMP__c = 4;
        accLevel1.RMS_Parent_Account__c = acc.id;
        
        insert accLevel1;
    }
}