src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mailing_Billing_City_WMP__c</fullName>
        <label>Mailing/Billing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Billing_Country_WMP__c</fullName>
        <label>Mailing/Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Panama</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>Saudi Arabia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>Tasmania</fullName>
                </value>
                <value>
                    <fullName>Trinidad and Tobago</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>Virgin Islands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_Billing_State_WMP__c</fullName>
        <label>Mailing/Billing State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_Billing_Street_WMP__c</fullName>
        <label>Mailing/Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Billing_Zip_Postal_Code_WMP__c</fullName>
        <label>Mailing/Billing Zip/Postal Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Account_Support_Team_WMP__c</fullName>
        <inlineHelpText>For Inform, the following support groups support the following products:

Inform NC = RMS, FBR, IQ, Analytics, Jail, Legacy VisionAIR

Inform IA = CAD, Mobile

Inform 911 = Only 911 products</inlineHelpText>
        <label>Account Support Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform 911</fullName>
                </value>
                <value>
                    <fullName>Inform IA</fullName>
                </value>
                <value>
                    <fullName>Inform NC</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Respond</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
                <value>
                    <fullName>IMC</fullName>
                    <color>#78C953</color>
                    <label>IMC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestActiveServiceContractsForAccount.cls
@isTest (seeAllData=true)
private class TestActiveServiceContractsForAccount {      
    static testMethod void TestUpdateServiceContracts() 
    {
	        // TO DO: implement unit test
	    for(ServiceContract svcContract : [Select Id, AccountId,Contract_Type__c From ServiceContract 
		Where (Contract_Status_WMP__c = 'Active' OR Contract_Status_WMP__c = 'Installed Not Live' 
	    OR Contract_Status_WMP__c = 'Renewal Due' 
	    OR Contract_Status_WMP__c = 'No HW Support, Software Only') Limit 1])
	    {
	       svcContract.BillingCity ='Dallas';
	       
	       update svcContract;
	        
	    }
    }        
    
    static testMethod void TestDeleteServiceContracts() 
    {
	        // TO DO: implement unit test
	    for(ServiceContract svcContract : [Select Id, AccountId,Contract_Type__c From ServiceContract 
		Where (Contract_Status_WMP__c = 'Active' OR Contract_Status_WMP__c = 'Installed Not Live' 
	    OR Contract_Status_WMP__c = 'Renewal Due' 
	    OR Contract_Status_WMP__c = 'No HW Support, Software Only') AND id='810n00000004DHc' limit 1])
	    {
	        
	       delete svcContract;
	       
	    }
    }    
    static testMethod void TestInsertServiceContracts() 
    {
	    Account a = new Account();
        a.Name = 'Test Account';
        a.Mailing_Billing_Street_WMP__c = 'street';
        a.Mailing_Billing_City_WMP__c = 'city';
        a.Mailing_Billing_State_WMP__c = 'state';
        a.Mailing_Billing_Zip_Postal_Code_WMP__c = '12345';
        a.Mailing_Billing_Country_WMP__c = 'us';
        insert a;
        
        Contact c = new Contact();
        c.AccountId = a.Id;
        c.LastName = 'Test cont';
        insert c;
        
	    ServiceContract svcContract = new ServiceContract();
	    svcContract.Name = 'Test';
		svcContract.AccountId= a.Id;
		svcContract.Contract_Type__c='IMC';
		svcContract.Contract_Status_WMP__c='Active';
		svcContract.Account_Support_Team_WMP__c='IMC';
		svcContract.StartDate =System.now().date();
		svcContract.EndDate = System.now().date() +1;
		svcContract.ActivationDate =System.now().date()+20;
		svcContract.Type_of_Support_WMP__c='24/7';
		svcContract.Support_Owner__c= UserInfo.getuserId();
		svcContract.Product_Family_WMP__c='IMC';
		 
		insert svcContract;    
		 
    }
}