src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Contract</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Contract Amendment</fullName>
                </value>
                <value>
                    <fullName>Sales Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Derived_Prd_Family_from_Contract_Type__c</fullName>
        <description>This field is used to map the product family to the contract type and allows for filtering in the Knowledge base.  This field should never be on the contract page layout.</description>
        <formula>IF( ISPICKVAL( Contract_Type__c , &quot;Billing&quot;) , &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;EMS CAD&quot;) , &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;FDC&quot;), &quot;EMS&quot;, 
 IF( ISPICKVAL( Contract_Type__c , &quot;Fusion ePCR&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;Fusion Online&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;IMC&quot;), &quot;IMC&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;SBS&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;Sweet-Online&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;VisiNet&quot;), &quot;VisiNet&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;AVeL&quot;), &quot;EMS&quot;,
 IF( ISPICKVAL( Contract_Type__c , &quot;VisionAIR&quot;), &quot;VisionAIR&quot;,
&quot;Unknown&quot;
)))))))))))</formula>
        <label>Derived Prd Family from Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>IQ</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/NewAvailableDownloadsController.cls
// ==================================================================================
//   Object: NewAvailableDownloadsController
//  Company: Tritech
//   Author: Mohan Kumar (Sales Optimizer)
// Comments: List the file from the FTP server
// ==================================================================================
//  Changes: 2012-11-20 Initial version.
// ==================================================================================

public with sharing class NewAvailableDownloadsController {
    
    public String folderNames {get;set;}
    
    public NewAvailableDownloadsController() {
		
		User portalUser = [SELECT ContactId FROM User WHERE Id = :Userinfo.getUserId()];
      	system.debug('getProductFamiliesByContract: portalUser contact [' + portalUser.ContactId + ']');
      
      	if (portalUser.ContactId != null) {
        	Contact cnct = [SELECT AccountId FROM Contact WHERE Id = :portalUser.ContactId];
        
	        if (cnct.AccountId != null) {
	          
	          //Get the Account this contact is associated with as that has the definitive product family value
	          List<Account> accounts = [SELECT Id FROM Account WHERE Id = :cnct.AccountID];
	          Account acct;
	          if (accounts.size() > 0) {
	            acct = accounts.get(0);
	          }
	          
	          if (acct != null) {
	            
	            //get the active contracts for this account
	            List<ServiceContract> activeContracts = [SELECT Id, Contract_Type__c, Product_Family_WMP__c, Derived_Prd_Family_from_Contract_Type__c FROM ServiceContract WHERE AccountId = :acct.Id AND Contract_Status_WMP__c = 'Active'];
	            
	            //set the available product families based on the values on the contract
	            List<String> activeContractTypes = new List<String>();
	            folderNames = '';
	            for (ServiceContract contract : activeContracts) {
					if(folderNames != null && contract.Product_Family_WMP__c != null && !folderNames.contains(contract.Product_Family_WMP__c)) {
						if(folderNames != '') {
							folderNames += ',' + contract.Product_Family_WMP__c;
						} else {
							folderNames = contract.Product_Family_WMP__c;
						}
					}
	            }
	            System.debug('folderNames:'+folderNames);
	          }
	        }
      	}
	}
}