src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mailing_Billing_City_WMP__c</fullName>
        <label>Mailing/Billing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Billing_Country_WMP__c</fullName>
        <label>Mailing/Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Panama</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>Saudi Arabia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>Tasmania</fullName>
                </value>
                <value>
                    <fullName>Trinidad and Tobago</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>Virgin Islands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_Billing_State_WMP__c</fullName>
        <label>Mailing/Billing State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_Billing_Street_WMP__c</fullName>
        <label>Mailing/Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Billing_Zip_Postal_Code_WMP__c</fullName>
        <label>Mailing/Billing Zip/Postal Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Account_Type__c</fullName>
        <label>xMaster Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Multi-Agency Co-located</fullName>
                </value>
                <value>
                    <fullName>Multi-Agency Consolidated</fullName>
                </value>
                <value>
                    <fullName>Partner/Vendor</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>Agency Accounts</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PictId__c</fullName>
        <inlineHelpText>Enter a document id to an image file with a picture of the contact</inlineHelpText>
        <label>PictId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestScheduleBatchVerifyPictureDocument.cls
/*********************************************************************************
* Test Class: {TestScheduleBatchVerifyPictureDocument}
* Created by {Madan Vishwakarma}, Navivo, {DateCreated 03/31/2014}
----------------------------------------------------------------------------------
* Purpose/Methods:
* - {ScheduleBatchVerifyPictureDocument/BatchVerifyPictureDocument Unit Tested by this Test Class.}
----------------------------------------------------------------------------------
* Utility Test Data: {}
----------------------------------------------------------------------------------
* History:
* - VERSION DEVELOPER NAME DATE DETAIL FEATURES
1.0 Madan Vishwakarma 03/31/2014 INITIAL DEVELOPMENT
2.0 Name MM/DD/YYYY UDAC WIRE FRAME CHANGES
*********************************************************************************/

@isTest
private class TestScheduleBatchVerifyPictureDocument {

    static testMethod void myUnitTest() {
    	Account a = new Account();
    	a.Name = 'test';
    	a.Product_Family_WMP__c = 'EMS';
    	a.Master_Account_Type__c = 'Agency';
    	a.Phone = '1234567890';
    	a.Mailing_Billing_Street_WMP__c = 'test';
    	a.Mailing_Billing_City_WMP__c = 'test';
    	a.Mailing_Billing_State_WMP__c = 'test';
    	a.Mailing_Billing_Zip_Postal_Code_WMP__c = '123456';
    	a.Mailing_Billing_Country_WMP__c = 'USA';
    	insert a;
    	
    	Folder f = [Select f.Id From Folder f Where DeveloperName = 'TriTech_Protal_User_Photos' Limit 1];

    	Document d = new Document();
    	d.ContentType = 'testContent';
    	d.Name = 'test';
    	d.Type = 'testPicture';
    	d.FolderId = f.Id;
    	insert d;
    	
    	Contact c = new Contact();
    	c.LastName = 'test';
    	c.PictId__c = d.Id;
    	c.AccountId = a.Id;
    	insert c;
    	
    	BatchVerifyPictureDocument batchObj = new BatchVerifyPictureDocument();
		Test.StartTest();
		database.executebatch(batchObj, 10);
		
		ScheduleBatchVerifyPictureDocument schedule = new ScheduleBatchVerifyPictureDocument();
		SchedulableContext context; 
        schedule.execute(context);
		Test.StopTest();
    }
}