src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracking checkbox for clients of TriTech, any division</description>
        <label>Client</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Contact_Date_Time_WMP__c</fullName>
        <label>Customer Contact Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Occured_After_Upgrade_WMP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Occurred After Upgrade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_Defect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential Defect</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Potential_Defect__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Potential Defect, Enhancement</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Potential_Defect__c</referenceTo>
        <relationshipLabel>Associated Tickets</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reported_Major_Version_WMP__c</fullName>
        <inlineHelpText>Choose your TriTech Software Version</inlineHelpText>
        <label>Reported Major Version</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undecided</fullName>
                </value>
                <value>
                    <fullName>7.10</fullName>
                </value>
                <value>
                    <fullName>7.9 SP1</fullName>
                </value>
                <value>
                    <fullName>7.0</fullName>
                </value>
                <value>
                    <fullName>6.7</fullName>
                </value>
                <value>
                    <fullName>6.6</fullName>
                </value>
                <value>
                    <fullName>6.5</fullName>
                </value>
                <value>
                    <fullName>6.4 SP5</fullName>
                </value>
                <value>
                    <fullName>6.4.SP4</fullName>
                    <label>6.4 SP4</label>
                </value>
                <value>
                    <fullName>6.4.SP3</fullName>
                    <label>6.4 SP3</label>
                </value>
                <value>
                    <fullName>6.4.SP2</fullName>
                    <label>6.4 SP2</label>
                </value>
                <value>
                    <fullName>6.4.SP1</fullName>
                </value>
                <value>
                    <fullName>6.4</fullName>
                </value>
                <value>
                    <fullName>6.3</fullName>
                </value>
                <value>
                    <fullName>6.2</fullName>
                </value>
                <value>
                    <fullName>6.1</fullName>
                </value>
                <value>
                    <fullName>6.0</fullName>
                </value>
                <value>
                    <fullName>5.15</fullName>
                </value>
                <value>
                    <fullName>5.14</fullName>
                </value>
                <value>
                    <fullName>5.13</fullName>
                </value>
                <value>
                    <fullName>5.12</fullName>
                </value>
                <value>
                    <fullName>5.11 SP2</fullName>
                </value>
                <value>
                    <fullName>5.11 SP1</fullName>
                </value>
                <value>
                    <fullName>5.11</fullName>
                </value>
                <value>
                    <fullName>5.10 SP1</fullName>
                </value>
                <value>
                    <fullName>5.10</fullName>
                </value>
                <value>
                    <fullName>5.9 SP1</fullName>
                </value>
                <value>
                    <fullName>5.9</fullName>
                </value>
                <value>
                    <fullName>5.8 SP13</fullName>
                </value>
                <value>
                    <fullName>5.8 SP12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Issue_Summary_WMP__c</fullName>
        <label>Short Issue Summary</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Potential_Defect__c.object
<CustomObject>
    <description>Potential Defect ticket object.  Ticket record types include Potential Defects and Enhancement tickets.</description>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Defect Ticket Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assessing Issue</fullName>
                    <default>true</default>
                    <label>Assessing Issue</label>
                </value>
                <value>
                    <fullName>Targeted for Future Release</fullName>
                </value>
                <value>
                    <fullName>Fix for Release in Progress</fullName>
                </value>
                <value>
                    <fullName>QA complete - Release</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Modules Schedule for New Platform</fullName>
                </value>
                <value>
                    <fullName>Configuration Issue</fullName>
                    <color>#FF0000</color>
                    <label>Configuration Issue</label>
                </value>
                <value>
                    <fullName>Customer Request</fullName>
                    <color>#FF0000</color>
                    <label>Customer Request</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <color>#FF0000</color>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>Fix ready for Release</fullName>
                    <color>#FF0000</color>
                    <label>Fix ready for Release</label>
                </value>
                <value>
                    <fullName>No Longer in General Use</fullName>
                    <color>#FF0000</color>
                    <label>No Longer in General Use</label>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                    <color>#FF0000</color>
                    <label>Out of Scope</label>
                </value>
                <value>
                    <fullName>Unable to Reproduce</fullName>
                    <color>#FF0000</color>
                    <label>Unable to Reproduce</label>
                </value>
                <value>
                    <fullName>Works as Designed</fullName>
                    <color>#FF0000</color>
                    <label>Works as Designed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Potential Defect</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Supportable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Support Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestauPotentialDefectTrigger.cls
//author: Mohan (Navivo)
//Date: 10-10-2013
@isTest(seeAllData=true)
private class TestauPotentialDefectTrigger {

    static testMethod void myUnitTest1() {
        Id pdRecordTypeId = [Select r.SobjectType, r.Name, r.Id From RecordType r Where Name = 'Potential Defect' and SobjectType = 'Potential_Defect__c'].Id;
        
        Product2 prod = new Product2();
        prod.Name = 'test prod';
        prod.IsActive = true;
        prod.Supportable__c = true;
        insert prod;
        
        Potential_Defect__c pd = new Potential_Defect__c();
        pd.Name = 'test';
        pd.RecordTypeId = pdRecordTypeId;
        pd.Priority__c = '3';
        insert pd;
        
        Potential_Defect__c pd1 = new Potential_Defect__c();
        pd1.Name = 'test';
        pd1.RecordTypeId = pdRecordTypeId;
        pd1.Priority__c = '3';
        insert pd1;
        
        RecordType rType = [Select r.SobjectType, r.Name, r.Id From RecordType r Where r.SobjectType='Case' and r.Name = 'Customer Support Ticket' limit 1];
        Case cse = new Case();
        cse.ProductId = prod.Id;
        cse.Short_Issue_Summary_WMP__c = 'Error when creating new product';
        cse.Priority = 'P2';
        cse.Subject = 'Issue with new product';
        cse.Occured_After_Upgrade_WMP__c = true;
        cse.Reported_Major_Version_WMP__c = '5.9';
        cse.Status = 'Closed';
        cse.RecordTypeId = rType.Id;
        cse.Customer_Contact_Date_Time_WMP__c = System.now();
        cse.Potential_Defect__c = pd.Id;
        insert cse;
        
        cse.Potential_Defect__c = null;
        update cse;
        
        cse.Potential_Defect__c = pd1.Id;
        update cse;
    }
    
    static testMethod void myUnitTest2() {
        Id pdRecordTypeId = [Select r.SobjectType, r.Name, r.Id From RecordType r Where Name = 'Potential Defect' and SobjectType = 'Potential_Defect__c'].Id;
        
        Product2 prod = new Product2();
        prod.Name = 'test prod';
        prod.IsActive = true;
        prod.Supportable__c = true;
        insert prod;
        
        Potential_Defect__c pd = new Potential_Defect__c();
        pd.Name = 'test';
        pd.RecordTypeId = pdRecordTypeId;
        pd.Priority__c = '3';
        insert pd;
        
        RecordType rType = [Select r.SobjectType, r.Name, r.Id From RecordType r Where r.SobjectType='Case' and r.Name = 'Customer Support Ticket' limit 1];
        Case cse = new Case();
        cse.ProductId = prod.Id;
        cse.Short_Issue_Summary_WMP__c = 'Error when creating new product';
        cse.Priority = 'P2';
        cse.Subject = 'Issue with new product';
        cse.Occured_After_Upgrade_WMP__c = true;
        cse.Reported_Major_Version_WMP__c = '5.9';
        cse.Status = 'Closed';
        cse.RecordTypeId = rType.Id;
        cse.Customer_Contact_Date_Time_WMP__c = System.now();
        cse.Potential_Defect__c = pd.Id;
        insert cse;
        
        pd.Ticket_Status__c = 'Fix for Release in Progress';
        update pd;
    }
    
    static testMethod void Dotest(){
        
        Test.startTest();
        
        Profile portalProfile = [ select Id from Profile where Name = 'TriTech Portal Manager' Limit 1];
        List<Profile> profileList = [Select Id From Profile Where Name = 'System Administrator'];
        List<UserRole> uRoleList = [Select Id From UserRole Where Name = 'TriTech Sales Manager' limit 1];
        String str = System.now().getTime().intValue().format();
        str = str.replaceAll(',', '');
        User u1 = new User();
        u1.Email = 'portalTestUser' + str + '@test.com';
        u1.Alias = 'prts';
        u1.TimeZoneSidKey = 'America/New_York';
        u1.LocaleSidKey = 'ca';
        u1.EmailEncodingKey = 'UTF-8';
        u1.ProfileId = profileList[0].Id;
        u1.LanguageLocaleKey = 'en_US';
        u1.FirstName = 'testFN';
        u1.LastName = 'testLN';
        u1.username= 'portalTestUser' + str + '@test.com';
        u1.UserRoleId = uRoleList[0].Id;
        u1.CompanyName = 'Test Company';
        insert u1;
        
        System.runAs(u1) {
            Account a = new Account();
            a.Name = 'Test Account';
            a.Client__c = true;
            insert a;
            
            Contact c = new Contact();
            c.AccountId = a.Id;
            c.LastName = 'Test cont';
            c.MailingStreet = 'street';
            c.MailingCity = 'city';
            c.MailingState = 'state';
            c.MailingPostalCode = '12345';
            c.MailingCountry = 'us';
            insert c;
            str = System.now().getTime().intValue().format();
            str = str.replaceAll(',', '');
            User u2 = new User();
            u2.Email = 'testBatchIdeasReport' + str + '@test.com';
            u2.Alias = 'prts';
            u2.TimeZoneSidKey = 'America/New_York';
            u2.LocaleSidKey = 'ca';
            u2.EmailEncodingKey = 'UTF-8';
            u2.ProfileId = portalProfile.Id;
            u2.LanguageLocaleKey = 'en_US';
            u2.FirstName = 'testFN';
            u2.LastName = 'testLN';
            u2.username= 'testBatchIdeasReport' + str + '@test.com';
            u2.ContactId = c.Id;
            u2.CompanyName = 'Test Company';
            insert u2;
            
            Id pdRecordTypeId = [Select r.SobjectType, r.Name, r.Id From RecordType r Where Name = 'Potential Defect' and SobjectType = 'Potential_Defect__c'].Id;
            
            Product2 prod = new Product2();
            prod.Name = 'test prod';
            prod.IsActive = true;
            prod.Supportable__c = true;
            insert prod;
            
            Potential_Defect__c pd = new Potential_Defect__c();
            pd.Name = 'test';
            pd.RecordTypeId = pdRecordTypeId;
            pd.Priority__c = '3';
            insert pd;
            
            Potential_Defect__c pd1 = new Potential_Defect__c();
            pd1.Name = 'test';
            pd1.RecordTypeId = pdRecordTypeId;
            pd1.Priority__c = '3';
            insert pd1;
            
            RecordType rType = [Select r.SobjectType, r.Name, r.Id From RecordType r Where r.SobjectType='Case' and r.Name = 'Customer Support Ticket' limit 1];
            Case cse = new Case();
            cse.ProductId = prod.Id;
            cse.Short_Issue_Summary_WMP__c = 'Error when creating new product';
            cse.Priority = 'P2';
            cse.Subject = 'Issue with new product';
            cse.Occured_After_Upgrade_WMP__c = true;
            cse.Reported_Major_Version_WMP__c = '5.9';
            cse.Status = 'Closed';
            cse.RecordTypeId = rType.Id;
            cse.Customer_Contact_Date_Time_WMP__c = System.now();
            cse.Potential_Defect__c = pd.Id;
            cse.ownerId = u2.Id;
            insert cse;
            
            
            
            System.runAs(u2) {
                try {
                    cse.Potential_Defect__c = null;
                    update cse;
                } catch(Exception ex) {}
                
            }
        }
    }
}