src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CPQ_Quote_Number__c</fullName>
        <label>CPQ Quote Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Click the icon to associate a contact from this account to the opportunity</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <inlineHelpText>Add-On/Extension/Upgrade: Any add-on/extension/upgrade to existing system already installed and under maintenance
New Major System: Any new major system (ie Inform CAD, Inform RMS, etc.) whether account is new or existing
911 System: Any standalone deal</inlineHelpText>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911 System</fullName>
                </value>
                <value>
                    <fullName>Add-On/Extension/Upgrade</fullName>
                    <default>true</default>
                    <label>Add-On/Extension/Upgrade</label>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
                <value>
                    <fullName>New Major System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gross_Margin__c</fullName>
        <inlineHelpText>Overall quote Gross Margin calculation</inlineHelpText>
        <label>Gross Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <inlineHelpText>Choose the appropriate price book for the quote associated with this opportunity.</inlineHelpText>
        <label>Price Book</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>GSA</fullName>
                </value>
                <value>
                    <fullName>Perform</fullName>
                </value>
                <value>
                    <fullName>Respond</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
                <value>
                    <fullName>Rapid Implementation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <inlineHelpText>Please enter the product family being proposed in the opportunity.</inlineHelpText>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ETI Hosted</fullName>
                </value>
                <value>
                    <fullName>ETI On Premise</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>Insight</fullName>
                </value>
                <value>
                    <fullName>IP911</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Perform</fullName>
                </value>
                <value>
                    <fullName>Respond</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>TT911</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products_Required__c</fullName>
        <inlineHelpText>For Inform quotes, please choose all products that apply to this Opportunity</inlineHelpText>
        <label>Product(s) Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>911 Consulting</fullName>
                </value>
                <value>
                    <fullName>Accident Reporting (Extend)</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Data Vault</fullName>
                </value>
                <value>
                    <fullName>DispatchNow</fullName>
                </value>
                <value>
                    <fullName>eCitations (Extend)</fullName>
                </value>
                <value>
                    <fullName>FBR</fullName>
                </value>
                <value>
                    <fullName>FBR (Extend)</fullName>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Fire Records</fullName>
                </value>
                <value>
                    <fullName>GIS Services</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Insight AVL</fullName>
                </value>
                <value>
                    <fullName>Insight Dispatch</fullName>
                </value>
                <value>
                    <fullName>Insight Mobile</fullName>
                </value>
                <value>
                    <fullName>IQ/Analytics</fullName>
                </value>
                <value>
                    <fullName>IQResponse</fullName>
                </value>
                <value>
                    <fullName>Jail</fullName>
                </value>
                <value>
                    <fullName>Jail Extend</fullName>
                </value>
                <value>
                    <fullName>LETG Add On</fullName>
                </value>
                <value>
                    <fullName>LETG eCitations</fullName>
                </value>
                <value>
                    <fullName>Mapping (Zuercher)</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Municipal Courts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <description>If quote number is Null, then workflow &quot;Set Quote #&quot; will populate it with the CPQ Quote Number value.  This will accommodate both legacy quote number entries and new CPQ quote number entries.</description>
        <label>Quote Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <description>Quote sales order number</description>
        <label>Sales Order Number</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extended_Price__c</fullName>
        <formula>Quantity *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Extended Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Gross_margin__c</fullName>
        <label>Gross margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maintenance_Amount__c</fullName>
        <label>Maintenance Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Support_Level__c</fullName>
        <label>Support Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/classes/CloneOpp.cls
public with sharing class CloneOpp {
    private String oppId;
    private Opportunity caseObj;
    private Opportunity copyCaseObj;
    public Opportunity ClonedOpportunity {get;set;}
    public Opportunity NewOpportunity {get;set;} 
    public Boolean showNewOppButton {get;set;}
    public String LaunchMode {get;set;}      
    GuidedSelling__GuidedSellingSettings__c orgSettings = null;    
    
    public CloneOpp (ApexPages.StandardController controller) {
        caseObj = new Opportunity();
        
        
    oppId =  System.currentPageReference().getParameters().get('id');
        for( Opportunity c:[ Select c.Owner.id,c.Name,c.Account.id,c.Sales_Order_Number__c,c.Contact__c,c.type,c.Probability,c.Products_Required__c,c.Deal_Type__c,c.RecordType.Id,c.Product_Family_WMP__c,c.Price_Book__c,c.RecordType.name,c.leadsource,c.RecordTypeId,
                        c.StageName,c.Quote_Number__c
                        From Opportunity c where id =: oppId]){
            caseObj = c;
        }               
    }
    
    public Pagereference doClone(){
        Pagereference pr = null;
        try{
            System.debug('Start : doClone ');
            System.debug('caseObj.StageName : ' + caseObj.StageName);
            if((caseObj.StageName == 'Booked')||(caseObj.StageName == 'Closed Won'))
            {
            System.debug('caseObj.RecordType.Name : ' + caseObj.RecordType.Name);
            //if((caseObj.RecordType.Name != 'Tritech Change Order')&&(caseObj.RecordType.Name != 'Zuercher Change Order'))
            //{
            //assigning values to new opportunity
            //SObject record = ProcessSchemaInfo(ClonedOpportunity.Id);
            Opportunity OpportunityRecordQueried = caseObj;     
            NewOpportunity = OpportunityRecordQueried.clone(false);
            NewOpportunity.Name = NewOpportunity.Name + ' Copy'; 
            NewOpportunity.CloseDate = system.today() + 30;
            NewOpportunity.StageName = 'Active Opportunity';
            NewOpportunity.Probability = 5;
            insert NewOpportunity;         
            
            //NewOpportunity.Owner = caseObj.Owner;
            
            //NewOpportunity.Account = caseObj.Account;
            //NewOpportunity.Sales_Order_Number__c = caseObj.Sales_Order_Number__c;
           // NewOpportunity.Contact__c = caseObj.Contact__c;
            //NewOpportunity.Products_Required__c = caseObj.Products_Required__c;
            
            //NewOpportunity.Original_Quote_Number__c = caseObj.Quote_Number__c;
            //NewOpportunity.Deal_Type__c = 'Change Order';
            //NewOpportunity.LeadSource = 'Customer Request';
            //NewOpportunity.Type = 'Existing Business';
            
            //string quonum = caseObj.Quote_Number__c.ToUpperCase().substring(0,9);
            //quonum = quonum.ToUpperCase().replace('QUO','ORD');
            //string variable = quonum.substring(4,9);
            //String[] variables = new String[]{'%' + variable + '%'};
            //variable = string.valueof(variables);
           // variable = variable.substring(1,8);
            //system.debug('Variable is: ' + variable);
            //determining number of quote versions
            //aggregateresult  ar = database.query('select count(id) result from opportunity where quote_number__c like \''+ variable + '\''); 
            //integer total = integer.valueof(ar.get('result'));              
            //system.debug('new number is ' + total);
            
            //formatting the new Sales Order revision number to be -XXXX
            //if(total == 0)
              //  {quonum = quonum + '-0001';}
            //if(total > 0 && total < 10)
            //    {quonum = quonum + '-000' + (total + 1);}
            //if(total >9 && total < 100)
            //    {quonum = quonum + '-00' + (total + 1);}
            //if(total > 99 && total < 1000)
            //    {quonum = quonum + '-0' + (total + 1);}
            //if(total > 999)
            //    {quonum = quonum + '-' + (total + 1);}    
                            
            //NewOpportunity.Quote_Number__c = quonum;
            //NewOpportunity.Name = 'Change Order - ' + total + ' ' + caseObj.Name;
            //system.debug('Count = ' + total);
            
            NewOpportunity.Probability = caseObj.Probability;
            //System.debug('The value of stage is: ' + caseObj.StageName);
            //System.debug('The value of RecordType is: ' + caseObj.RecordType.Name);
            if((caseObj.StageName == 'Booked')||(caseObj.StageName == 'Closed Won'))
            {
            if ((caseObj.RecordType.Name == 'Tritech Competitive') || (caseObj.RecordType.Name == 'Tritech Non-Competitive'))
            {
                //inserting the Tritech specific required data elements
                NewOpportunity.RecordTypeid = [Select Id from recordtype where name = 'Tritech Change Order'].id;
                NewOpportunity.Description = 'Change Order for Sales Order: ' + caseObj.Sales_Order_Number__c;
                NewOpportunity.StageName = 'Active Opportunity';
                NewOpportunity.Probability = 5;
            }
            else if ((caseObj.RecordType.Name == 'Zuercher Non-Competitive') || (caseObj.RecordType.Name == 'Zuercher Competitive'))
            {
                //inserting the Z specific required elements
                NewOpportunity.RecordTypeid = [Select Id from recordtype where name = 'Zuercher Change Order'].id;
                NewOpportunity.StageName = 'Active Opportunity';
                NewOpportunity.Probability = 5;
            }
            }
            
            
            //NewOpportunity.Product_Family_WMP__c = caseObj.Product_Family_WMP__c;
            //NewOpportunity.Price_Book__c = caseObj.Price_Book__c;
            
            //inserting the Sales Order record type opportunity
            upsert NewOpportunity;
            
            //building the list of Opportunity line items
            Map<Id, Opportunity> cloneOppMap = new Map<Id, Opportunity>();
            List<OpportunityLineItem> cloneOppLineItemList = new List<OpportunityLineItem>();
            List<OpportunityLineItem> oldOppLineItemList = [Select UnitPrice, Quantity, Discount,GRoss_Margin__c,PricebookEntryId, ProductCode,Functional_Area__c,Type__c,Extended_Price__c,Cost__c,Support_Level__c,Maintenance_Amount__c,Charge_Type__c,OpportunityId, ListPrice, Id, Description From OpportunityLineItem where OpportunityId = :oppId];
            system.debug('********** OLD Opp Line Items List-1: '+ oldOppLineItemList);
            for(OpportunityLineItem oldlineitem : oldOppLineItemList) 
            {
            //copying the old line items to the new opportunity list   
            OpportunityLineItem newlineitem = oldlineitem.clone(false, true);
            newlineitem.OpportunityId = NewOpportunity.id;
            cloneOppLineItemList.add(newlineitem);
            }
            system.debug('********** Cloned Opp Line Item List-1: '+ cloneOppLineItemList);
            //inserting the line items into the newly created opportunity
            //upsert cloneOppLineItemList;
                                                                            
            //defining the page to be returned to the user once the inserts have completed 
            pr = new PageReference('/' + NewOpportunity.id + '/e?saveURL=/' + NewOpportunity.Id + '&00N80000004ZqvX=');
            pr.setRedirect(true);
            //}
            //else
            //{
            //  string error = caseObj.RecordType.name;
             //   caseObj.addError('Change Orders can only be created on the Original Opportunity.' + error);
            //    System.debug('Change Orders can only be created on the Original Opportunity.');
            //}
            }
            else
            {
                caseObj.addError('Only Opportunities with a Booked stage are available to create a Change Order.');
                System.debug('Change Orders can only be created on the Original Opportunity.');
            }
            System.debug('End : doClone');
        }
        catch(DMLException e ){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getDMLMessage(0))); 
            System.debug('Error : doClone action : ' + e.getDMLMessage(0));
            return null;  
        }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
            System.debug('Error : doClone action : ' + ex.getMessage());
            return null;  
        }
        //return pr;
        return null; 
    }        
    
    /*
        Copying quote in CPQ.
    */
    public PageReference CopyQuote() {
        
         try    
         {               
            System.debug(' Start : CopyQuote() '); 
             
            if((caseObj.StageName == 'Booked')||(caseObj.StageName == 'Closed Won'))
            {
                System.debug('caseObj.RecordType.Name : ' + caseObj.RecordType.Name);
            //  if((caseObj.RecordType.Name == 'Tritech Change Order')||(caseObj.RecordType.Name == 'Zuercher Change Order'))
            //  {
             //       caseObj.addError('Change Orders can only be created on the Original Opportunity.');
            //        return null;
                    //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'New Opportunity is not created. Having error in doClone action.'));
            //    }
            }
            else
            {
                caseObj.addError('Only Opportunities with a Booked stage are available to create a Change Order.'); 
                return null;
            }
                          
             if(NewOpportunity == null)
             {
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'New Opportunity is not created. Having error in doClone action.'));
                 //showNewOppButton = true;
                 return null;                 
             }
             
             if(caseObj == null)
             {
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Old Opportunity is null. Having error in doClone action.'));
                 //showNewOppButton = true;
                 return null;                 
             }
                          
             //string quonum = caseObj.Quote_Number__c.ToUpperCase().substring(0,9);
             string quonum = caseObj.Quote_Number__c.ToUpperCase();
             //system.debug('orig quote number' + quonum);
             quonum = quonum.ToUpperCase().replace('QUO','ORD');
                         
             string variable = quonum.substring(4);
             //string variable = quonum;
             system.debug (' quotenumber ' + variable); 
             //String[] variables = new String[]{'%' + variable + '%'};
             //variable = string.valueof(variables);
             //variable = variable.substring(1,8);
             system.debug('variable after changes' + variable);
             //determining number of quote versions
             variable = '\'%' + String.escapeSingleQuotes(variable.trim()) + '%\'';
             aggregateresult  ar = database.query('select count(id) result from opportunity where quote_number__c like ' + variable);
             
             integer total = integer.valueof(ar.get('result'));              
                         
             //formatting the new Sales Order revision number to be -XXXX
             if (total > 0)
                total = total - 1;
             if(total == 0)
                {quonum = quonum + '-0001';}
             if(total > 0 && total < 10)
                 {quonum = quonum + '-000' + (total);}
             if(total >9 && total < 100)
                 {quonum = quonum + '-00' + (total);}
             if(total > 99 && total < 1000)
                 {quonum = quonum + '-0' + (total);}
             if(total > 999)
                 {quonum = quonum + '-' + (total);}    
              if((caseObj.StageName == 'Booked')||(caseObj.StageName == 'Closed Won'))
            {
            if ((caseObj.RecordType.Name == 'Tritech Competitive') || (caseObj.RecordType.Name == 'Tritech Non-Competitive'))
            {
                //inserting the Tritech specific required data elements
                NewOpportunity.RecordTypeid = [Select Id from recordtype where name = 'Tritech Change Order'].id;
                NewOpportunity.Description = 'Change Order for Sales Order: ' + caseObj.Sales_Order_Number__c;
                NewOpportunity.StageName = 'Active Opportunity';
                NewOpportunity.Probability = 5;
            }
            else if ((caseObj.RecordType.Name == 'Zuercher Non-Competitive') || (caseObj.RecordType.Name == 'Zuercher Competitive'))
            {
                //inserting the Z specific required elements
                NewOpportunity.RecordTypeid = [Select Id from recordtype where name = 'Zuercher Change Order'].id;
                NewOpportunity.StageName = 'Active Opportunity';
                NewOpportunity.Probability = 5;
            }
            }
             if((caseObj.RecordType.Name != 'Tritech Change Order')&&(caseObj.RecordType.Name != 'Zuercher Change Order'))
             {               
                NewOpportunity.Quote_Number__c = quonum;
                NewOpportunity.CPQ_Quote_Number__c = quonum;
                NewOpportunity.StageName = 'Active Opportunity';
                NewOpportunity.Probability = 5;
             }
             Pagereference pr = null;
             String applicationUrl = getApplicationUrl('prod');             
             String serverUrl = 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/services/Soap/u/26.0/' + UserInfo.getOrganizationId(); 
             System.debug(' Old OpportunityId ' + caseObj.Id);             
             System.debug(' New OpportunityId ' + NewOpportunity.id);             
             // Login to CPQ with HMAC and Session Id                        
             String statusMsg = CloneOpportunityController.CopyQuote(UserInfo.getSessionId(), getHMACSignature(UserInfo.getSessionId()), UserInfo.getUserName(), applicationUrl, serverUrl, caseObj.Id, NewOpportunity.id);
             //String statusMsg = GuidedSelling.CloneOpportunityController.CopyQuote(UserInfo.getSessionId(), getHMACSignature(UserInfo.getSessionId()), UserInfo.getUserName(), endeavorCPQUrl, serverUrl, oppId, NewOpportunity.id);             
             System.debug('statusMsg : ' + statusMsg);             
             NewOpportunity.LeadSource = 'Customer Request';             
             NewOpportunity.Type = 'Existing Business';             
             NewOpportunity.Deal_Type__c = 'Change Order';             
             NewOpportunity.StageName = 'Active Opportunity';             
             NewOpportunity.Probability = 5;             
             
             if((caseObj.RecordType.Name != 'Tritech Change Order')&&(caseObj.RecordType.Name != 'Zuercher Change Order'))
             {                                
                NewOpportunity.Name = 'Change Order - ' + total + ' ' + caseObj.Name;
             }
             
             upsert NewOpportunity;                 
             
             if(statusMsg == 'ERROR')
             {
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Opportunity has been created and opportunityid is ' + NewOpportunity.id + '. Opportunity does not associate with CPQ quote or getting error during process CopyQuote workflow in CPQ.'));
                 showNewOppButton = true;
                 return null;                              
             }
             else
             {  
                 //defining the page to be returned to the user once the inserts have completed 
                 pr = new PageReference('/' + NewOpportunity.id + '/e?saveURL=/' + NewOpportunity.Id + '&00N80000004ZqvX=');
                 pr.setRedirect(true);
                 return pr;                               
             }                       
         } 
         catch (Exception e)
         {
            System.debug('Error : Copy Quote : ' + e.getMessage());             
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Opportunity has been created and opportunityid is ' + NewOpportunity.id + '. Opportunity does not associate with CPQ quote or getting error during process CopyQuote workflow in CPQ.'));
            return null;             
         }                       
    } 
    
    /*     
        Redirect to new opportunity.
    */
    public PageReference RedirectToNewOpportunity() {               
        return new PageReference('/'+ NewOpportunity.id);
    }
    
    /*
        Returns the HMAC encoded Signature for the given input.
    */
    public String getHMACSignature(string inputData)
    {
        string AuthenticationKey = null;                         
        orgSettings = getGuidedSellingSettings();
        AuthenticationKey = orgSettings.GuidedSelling__Authentication_Key__c;
        Blob mac = Crypto.generateMac('HmacSHA256', Blob.valueOf(inputData), Blob.valueOf(AuthenticationKey));
        String sig = EncodingUtil.urlEncode(EncodingUtil.base64Encode(mac), 'UTF-8');
        return sig;
    }
    
    /*
        Retrieves settings from the database.
    */
    public GuidedSelling__GuidedSellingSettings__c getGuidedSellingSettings()
    {
        if(orgSettings == null)
        {                
            GuidedSelling__GuidedSellingSettings__c[] settings = [Select Id,GuidedSelling__Authentication_Key__c, GuidedSelling__Organization_Name__c From GuidedSelling__GuidedSellingSettings__c];   
            if(settings.size() > 0)
                orgSettings = settings[0];
        }
        return orgSettings;      
    }
    
   public string getApplicationUrl(string mode)
   {
       string applicationUrl = null;                         
       orgSettings = getGuidedSellingSettings();
       applicationUrl = orgSettings.GuidedSelling__Organization_Name__c;              
       // Set dev url static values. 
       if(mode == 'dev')
       {
           if(applicationUrl.indexOf('https://cpqdev-') == -1) 
           { 
               if(applicationUrl.indexOf('https://') > -1) 
                   applicationUrl = applicationUrl.replace('https://', ''); 
               applicationUrl = 'https://cpqdev-' + applicationUrl; 
           } 
           if(applicationUrl.indexOf('.com') == -1) 
               applicationUrl += '.endeavorcpq.com'; 
       }
       else if(mode == 'test')
       {
           if(applicationUrl.indexOf('https://cpqtest-') == -1) 
           { 
               if(applicationUrl.indexOf('https://') > -1) 
                   applicationUrl = applicationUrl.replace('https://', ''); 
               applicationUrl = 'https://cpqtest-' + applicationUrl; 
           } 
           if(applicationUrl.indexOf('.com') == -1) 
               applicationUrl += '.endeavorcpq.com'; 
       }
       else if(mode == 'stage')
       {
           if(applicationUrl.indexOf('https://cpqstage-') == -1) 
           { 
               if(applicationUrl.indexOf('https://') > -1) 
                   applicationUrl = applicationUrl.replace('https://', ''); 
               applicationUrl = 'https://cpqstage-' + applicationUrl; 
           } 
           if(applicationUrl.indexOf('.com') == -1) 
               applicationUrl += '.endeavorcpq.com'; 
       }
       else
       {               
           if(applicationUrl.indexOf('https://') == -1) 
               applicationUrl = 'https://' + applicationUrl; 
           if(applicationUrl.indexOf('.com') == -1) 
               applicationUrl += '.endeavorcpq.com'; 
       }
       return applicationUrl;
   }
}