src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CAD_Parent_Fire_EMS_Users__c</fullName>
        <label>CAD Parent Fire EMS Users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD_Parent_Total_Sworn_Officers__c</fullName>
        <label>CAD Parent Total Sworn Officers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fire_Career__c</fullName>
        <label>Fire - Career</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Sworn_Personnel_WMP__c</fullName>
        <description>Field is currently locked down to read only to all users except for sys admins and users with the &quot;Account_Sworn Counts and Hierarchy Changes&quot; permission set associated to their user record.</description>
        <label>Number of Sworn Officers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMS_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Utilized to indicate the Agency&apos;s RMS Parent Account</inlineHelpText>
        <label>RMS Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMS_Parent_Total_Sworn_Officers__c</fullName>
        <label>RMS Parent Total Sworn Officers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trigger911Update__c</fullName>
        <label>Trigger911Update</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TriggerRMSUpdate__c</fullName>
        <label>TriggerRMSUpdate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TriggerUpdate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TriggerUpdate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X911_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Utilized to indicate the Agency&apos;s 911 Parent Account</inlineHelpText>
        <label>911 Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (911 Parent Account)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X911_Parent_Total_Sworn_Officers__c</fullName>
        <label>911 Parent Total Sworn Officers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Account_c.cls
/*
** Revision History
** 09/20/2016  Ken Becker Katch Consulting -  Initial Creation 
**
**
*/

public class Account_c {

  public static Boolean fromFutureMethod = true;
  //public static Boolean from911ParentFutureMethod = true;
  //public static Boolean fromRmsParentFutureMethod = true;
    
  public static void rollupSwornOfficerCount(map<Id,Account> accts, map<Id,Account> oldAccts, boolean isInsert){
    set<Id> remParentIds = new set<Id>();
    List<Id> accRecId = new List<Id>();
  
    for(Account a: accts.values()){
      if((a.TriggerUpdate__c == null?0:a.TriggerUpdate__c) == (oldAccts.get(a.Id).TriggerUpdate__c == null?0:oldAccts.get(a.Id).TriggerUpdate__c)){ 
        accRecId.add(a.Id);
      }
      if(a.ParentId == null){
        if(oldAccts.get(a.Id).ParentId<> null){
          remParentIds.add(oldAccts.get(a.Id).ParentId);
        }
      }
    }
    
    if(Account_c.fromFutureMethod) {
        UpdateRollUpFieldOnAccount.rollupSwornOfficerCount(accRecId, remParentIds, isInsert);        
    }
  }
  
  public static void rollup911SwornOfficerCount(map<Id,Account> accts, map<Id,Account> oldAccts, boolean isInsert){
    set<Id> remParentIds = new set<Id>();
    List<Id> accRecId = new List<Id>();
  
    for(Account a: accts.values()){
      if((a.Trigger911Update__c == null?0:a.Trigger911Update__c) == (oldAccts.get(a.Id).Trigger911Update__c == null?0:oldAccts.get(a.Id).Trigger911Update__c)){ 
        accRecId.add(a.Id);
      }
      if(a.X911_Parent_Account__c == null){
        if(oldAccts.get(a.Id).X911_Parent_Account__c <> null){
          remParentIds.add(oldAccts.get(a.Id).X911_Parent_Account__c);
        }
      }
    }
    
    if(Account_c.fromFutureMethod) {
        UpdateRollUpFieldOnAccount.rollup911SwornOfficerCount(accRecId, remParentIds, isInsert);        
    }
  }
  
  public static void rollupRMSSwornOfficerCount(map<Id,Account> accts, map<Id,Account> oldAccts, boolean isInsert){
    set<Id> remParentIds = new set<Id>();
    List<Id> accRecId = new List<Id>();
  
    for(Account a: accts.values()){
      if((a.TriggerRMSUpdate__c == null?0:a.TriggerRMSUpdate__c) == (oldAccts.get(a.Id).TriggerRMSUpdate__c == null?0:oldAccts.get(a.Id).TriggerRMSUpdate__c)){ 
        accRecId.add(a.Id);
      }
      if(a.RMS_Parent_Account__c == null){
        if(oldAccts.get(a.Id).RMS_Parent_Account__c <> null){
          remParentIds.add(oldAccts.get(a.Id).RMS_Parent_Account__c);
        }
      }
    }
    
    if(Account_c.fromFutureMethod) {
        UpdateRollUpFieldOnAccount.rollupRMSSwornOfficerCount(accRecId, remParentIds, isInsert);        
    }
  }
  
  public list<Account> rollupSwornOfficerCount(list<Account> accts){
    
    for(Account a: accts){
      if(a.ParentId == null){
        a.CAD_Parent_Total_Sworn_Officers__c = a.Number_of_Sworn_Personnel_WMP__c == null?0:a.Number_of_Sworn_Personnel_WMP__c;
        a.CAD_Parent_Fire_EMS_Users__c = a.Fire_Career__c == null?0:a.Fire_Career__c;
        a.triggerupdate__c = Datetime.now().getTime();
      }
      
      //Arpit 22-May-2018: Adding code for 911 Parent Account and RMS Account
      if(a.X911_Parent_Account__c == null) {
        a.X911_Parent_Total_Sworn_Officers__c = a.Number_of_Sworn_Personnel_WMP__c == null?0:a.Number_of_Sworn_Personnel_WMP__c;
        a.triggerupdate__c = Datetime.now().getTime();
      }
      
      if(a.RMS_Parent_Account__c == null) {
        a.RMS_Parent_Total_Sworn_Officers__c = a.Number_of_Sworn_Personnel_WMP__c == null?0:a.Number_of_Sworn_Personnel_WMP__c;
        a.triggerupdate__c = Datetime.now().getTime();
      }
      //End of Arpit 22-May-2018: Adding code for 911 Parent Account and RMS Account
    }
    return accts;
  }
}