src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Description__c</fullName>
        <inlineHelpText>Enter description of Asset</inlineHelpText>
        <label>Asset Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extended_Net_Price__c</fullName>
        <label>Extended Net Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Price_Per_Unit__c</fullName>
        <label>List Price Per Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_WMP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_WMP__c</fullName>
        <label>Asset Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order #</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Support_Price__c</fullName>
        <label>Support Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Under_Maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This Asset is covered under support maintenance</inlineHelpText>
        <label>Under Maintenance</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booked_Date__c</fullName>
        <label>Booked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Date__c</fullName>
        <description>Quote purchase order date</description>
        <label>Purchase Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <description>Quote sales order number</description>
        <label>Sales Order Number</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Converted_to_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extended_Net_Price__c</fullName>
        <label>Extended Net Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extended_Price__c</fullName>
        <formula>Quantity *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Extended Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Price_Per_Unit__c</fullName>
        <label>List Price Per Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maintenance_Amount__c</fullName>
        <label>Maintenance Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Support_Level__c</fullName>
        <label>Support Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Support_Level__c</fullName>
        <description>8 x 5 = 18%
24 x 7 = 22%
24 x 7 (911) = 18%
24 x 7 (Upgrade) = 25.88%
Perform = 18%
Pervasive = 25%
IQ 8 x 5 = 20%
24 x 7 &amp; 8 x 5 Tib = 18%</description>
        <inlineHelpText>8 x 5 = 18%
24 x 7 = 22%
24 x 7 (911) = 18%
24 x 7 (Upgrade) = 25.88%
Perform = 18%
Pervasive = 25%
IQ 8 x 5 = 20%
24 x 7 &amp; 8 x 5 Tib = 18%</inlineHelpText>
        <label>Support Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8 x 5</fullName>
                </value>
                <value>
                    <fullName>24 x 7</fullName>
                </value>
                <value>
                    <fullName>IQ 8 x 5</fullName>
                </value>
                <value>
                    <fullName>Perform</fullName>
                </value>
                <value>
                    <fullName>Pervasive</fullName>
                </value>
                <value>
                    <fullName>24 x 7 (911)</fullName>
                </value>
                <value>
                    <fullName>24 x 7 (Upgrade)</fullName>
                </value>
                <value>
                    <fullName>8 X 5 Tib</fullName>
                </value>
                <value>
                    <fullName>24 X 7 Tib</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template_Product_Category__c</fullName>
        <inlineHelpText>Utilized for assistance in categorizing items on generation templates</inlineHelpText>
        <label>Template Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAD Software Base</fullName>
                </value>
                <value>
                    <fullName>CAD Software Ancillary Module</fullName>
                </value>
                <value>
                    <fullName>CAD Software Interface</fullName>
                </value>
                <value>
                    <fullName>CAD Alternate Environment</fullName>
                </value>
                <value>
                    <fullName>Fire Records Base</fullName>
                </value>
                <value>
                    <fullName>Fire Records Service</fullName>
                </value>
                <value>
                    <fullName>Mobile Software Base</fullName>
                </value>
                <value>
                    <fullName>Mobile Software Ancillary Module</fullName>
                </value>
                <value>
                    <fullName>Mobile Software Interface</fullName>
                </value>
                <value>
                    <fullName>Mobile Alternate Environment</fullName>
                </value>
                <value>
                    <fullName>911 Software Base</fullName>
                </value>
                <value>
                    <fullName>911 Software Ancillary Module</fullName>
                </value>
                <value>
                    <fullName>911 Software Interface</fullName>
                </value>
                <value>
                    <fullName>911 Alternate Environment</fullName>
                </value>
                <value>
                    <fullName>RMS Software Base</fullName>
                </value>
                <value>
                    <fullName>RMS Software Ancillary Module</fullName>
                </value>
                <value>
                    <fullName>RMS Software Interface</fullName>
                </value>
                <value>
                    <fullName>RMS Alternate Environment</fullName>
                </value>
                <value>
                    <fullName>MNHS Software</fullName>
                </value>
                <value>
                    <fullName>FBR Software Base</fullName>
                </value>
                <value>
                    <fullName>FBR Software Interface</fullName>
                </value>
                <value>
                    <fullName>Jail Software Base</fullName>
                </value>
                <value>
                    <fullName>Jail Software Ancillary Module</fullName>
                </value>
                <value>
                    <fullName>Jail Software Interface</fullName>
                </value>
                <value>
                    <fullName>Jail Alternate Environment</fullName>
                </value>
                <value>
                    <fullName>IQ Software Base</fullName>
                </value>
                <value>
                    <fullName>IQ Software Interface</fullName>
                </value>
                <value>
                    <fullName>CAD Installation Service</fullName>
                </value>
                <value>
                    <fullName>CAD Training Service</fullName>
                </value>
                <value>
                    <fullName>CAD Implementation Service</fullName>
                </value>
                <value>
                    <fullName>Recurring Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Log</label>
    <nameField>
        <label>Sales Order Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateAssetsFromOppProduct.cls
public class CreateAssetsFromOppProduct {
    public string oppId {get; set;}
    
    public CreateAssetsFromOppProduct(ApexPages.StandardController sc) {
        oppId = sc.getId();
    }
    
    public PageReference doCreateAssests(){
        Opportunity currentOpp = null;
        for(Opportunity o : [Select Id, AccountId,  CloseDate, IsClosed,Sales_Order_Number__c,Purchase_Order_Date__c,Booked_Date__c  From Opportunity WHERE Id = :oppId ]){
            currentOpp = o;
        }
        
        if(currentOpp != null){
        
            if(currentOpp.IsClosed ){
                 OpportunityLineItem[] oppLines = [Select UnitPrice, Quantity, PricebookEntry.Product2Id, PricebookEntry.Product2.Name, Description, Converted_to_Asset__c,Maintenance_Amount__c,Support_Level__c,ListPrice,Extended_Price__c,Type__c  
                                      From OpportunityLineItem 
                                      where OpportunityId = :currentOpp.Id  and Converted_to_Asset__c = false  
                                      and
                    ((  
                        (
                            PricebookEntry.Product2.ProductCode Like '%SW%' 
                                                or PricebookEntry.Product2.ProductCode like '%Software%' 
                                            )
                                         and 
                        (
                            NOT PricebookEntry.Product2.Template_Product_Category__c like '%Maintenance%'
                        )
                                        )
                                         
                                     OR
                                            (
                            (PricebookEntry.Product2.ProductCode like '%GuidedSelling%') 
                                AND (
                                    (Type__c like 'Integrated Solution') 
                                    or (Type__c like 'Recurring Fee')
                                                        or (Type__c like 'Software Modification') 
                                    or (Type__c like 'third Party Software') 
                                    or (Type__c like 'Software')
                                    )
                        )
                    )]; 
                                                         
                                      
                Asset[] assets = new Asset[]{};
                Asset singleAsset = new Asset();
                //loop through the opportunity line items to create an asset associated with each opportunity line item
                for(OpportunityLineItem singleoppLine: oppLines)
                {
                    singleAsset = new Asset();
                    singleAsset.AccountId = currentOpp.AccountId;
                    singleAsset.Product_WMP__c = singleoppLine.PricebookEntry.Product2Id;
                    singleAsset.Quantity_WMP__c = singleoppLine.Quantity;
                    singleAsset.Price =  singleoppLine.UnitPrice;
                    singleAsset.Sales_Order__c =  currentOpp.Sales_Order_Number__c;
                    if(currentOpp.Booked_Date__c.format() != '')
                       { 
                        singleAsset.PurchaseDate = currentOpp.Booked_Date__c;
                       }
                    if(currentOpp.Booked_Date__c.format() == '')
                       { 
                        singleAsset.PurchaseDate = currentOpp.CloseDate;
                       }
                    singleAsset.List_Price_Per_Unit__c = singleoppLine.ListPrice;
                    singleAsset.Extended_Net_Price__c = singleoppLine.Extended_Price__c;
                    singleAsset.Status = 'Purchased';
                    singleAsset.Description = singleoppLine.Description;
                    singleAsset.Support_Price__c = singleoppLine.Maintenance_Amount__c;
                    singleAsset.Asset_Description__c = singleoppLine.Description;
                    if(singleoppLine.PricebookEntry.Product2.Name == 'CPQ Custom Product')
                    {
                        singleAsset.Name = singleoppLine.Description;
                    }
                    else
                    {
                        singleAsset.Name = singleoppLine.PricebookEntry.Product2.Name;
                    }
                    //if(singleoppLine.Maintenance_Amount__c > 0.00)
                    //{
                      // singleAsset.Under_Maintenance__c = true; 
                    //}
              
                    Assets.add(singleAsset);
                    singleoppLine.Converted_to_Asset__c = true;
                }
                try 
                {
                    Database.update(oppLines); 
                    Database.insert(assets);
                }
                catch (DMLException exp){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'OpportunityId:' + currentOpp.Id + 'AccountID:' + currentOpp.AccountId + 'CloseDate:' + currentOpp.Closedate+' Exception:' + exp.getMessage()));
                }
                //On success return a message to the calling program
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,   'Asset(s) created.'));
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This Operation is only allowed on Closed Won Opportunities'));
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Can\'t find opportunity product'));
        }
        return null;
    }
     
}