src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Reported_Major_Version_WMP__c</fullName>
        <inlineHelpText>Choose your TriTech Software Version</inlineHelpText>
        <label>Reported Major Version</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undecided</fullName>
                </value>
                <value>
                    <fullName>7.10</fullName>
                </value>
                <value>
                    <fullName>7.9 SP1</fullName>
                </value>
                <value>
                    <fullName>7.0</fullName>
                </value>
                <value>
                    <fullName>6.7</fullName>
                </value>
                <value>
                    <fullName>6.6</fullName>
                </value>
                <value>
                    <fullName>6.5</fullName>
                </value>
                <value>
                    <fullName>6.4 SP5</fullName>
                </value>
                <value>
                    <fullName>6.4.SP4</fullName>
                    <label>6.4 SP4</label>
                </value>
                <value>
                    <fullName>6.4.SP3</fullName>
                    <label>6.4 SP3</label>
                </value>
                <value>
                    <fullName>6.4.SP2</fullName>
                    <label>6.4 SP2</label>
                </value>
                <value>
                    <fullName>6.4.SP1</fullName>
                </value>
                <value>
                    <fullName>6.4</fullName>
                </value>
                <value>
                    <fullName>6.3</fullName>
                </value>
                <value>
                    <fullName>6.2</fullName>
                </value>
                <value>
                    <fullName>6.1</fullName>
                </value>
                <value>
                    <fullName>6.0</fullName>
                </value>
                <value>
                    <fullName>5.15</fullName>
                </value>
                <value>
                    <fullName>5.14</fullName>
                </value>
                <value>
                    <fullName>5.13</fullName>
                </value>
                <value>
                    <fullName>5.12</fullName>
                </value>
                <value>
                    <fullName>5.11 SP2</fullName>
                </value>
                <value>
                    <fullName>5.11 SP1</fullName>
                </value>
                <value>
                    <fullName>5.11</fullName>
                </value>
                <value>
                    <fullName>5.10 SP1</fullName>
                </value>
                <value>
                    <fullName>5.10</fullName>
                </value>
                <value>
                    <fullName>5.9 SP1</fullName>
                </value>
                <value>
                    <fullName>5.9</fullName>
                </value>
                <value>
                    <fullName>5.8 SP13</fullName>
                </value>
                <value>
                    <fullName>5.8 SP12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SCID__c</fullName>
        <description>This field is to receive the service contract from the portal user. The portal user does not have access to the Service Contract. Apex will update the service contract on the case using this field.</description>
        <label>SCID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCTY__c</fullName>
        <label>SCTY</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Account_Support_Team_WMP__c</fullName>
        <inlineHelpText>For Inform, the following support groups support the following products:

Inform NC = RMS, FBR, IQ, Analytics, Jail, Legacy VisionAIR

Inform IA = CAD, Mobile

Inform 911 = Only 911 products</inlineHelpText>
        <label>Account Support Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform 911</fullName>
                </value>
                <value>
                    <fullName>Inform IA</fullName>
                </value>
                <value>
                    <fullName>Inform NC</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Omega</fullName>
                </value>
                <value>
                    <fullName>Respond</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuercher_Suite_Version__c</fullName>
        <label>Zuercher Suite Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>7.10</fullName>
                </value>
                <value>
                    <fullName>7.9 SP1</fullName>
                </value>
                <value>
                    <fullName>7.0</fullName>
                </value>
                <value>
                    <fullName>6.7</fullName>
                </value>
                <value>
                    <fullName>6.6</fullName>
                </value>
                <value>
                    <fullName>6.5</fullName>
                </value>
                <value>
                    <fullName>6.4 SP5</fullName>
                </value>
                <value>
                    <fullName>6.4.SP4</fullName>
                </value>
                <value>
                    <fullName>6.4.SP3</fullName>
                </value>
                <value>
                    <fullName>6.4.SP2</fullName>
                </value>
                <value>
                    <fullName>6.4.SP1</fullName>
                </value>
                <value>
                    <fullName>6.4</fullName>
                </value>
                <value>
                    <fullName>6.3</fullName>
                </value>
                <value>
                    <fullName>6.2</fullName>
                </value>
                <value>
                    <fullName>6.1</fullName>
                </value>
                <value>
                    <fullName>6.0</fullName>
                </value>
                <value>
                    <fullName>5.15</fullName>
                </value>
                <value>
                    <fullName>5.14</fullName>
                </value>
                <value>
                    <fullName>5.13</fullName>
                </value>
                <value>
                    <fullName>5.12</fullName>
                </value>
                <value>
                    <fullName>5.11</fullName>
                </value>
                <value>
                    <fullName>5.10 SP1</fullName>
                </value>
                <value>
                    <fullName>5.10</fullName>
                </value>
                <value>
                    <fullName>5.9 SP1</fullName>
                </value>
                <value>
                    <fullName>5.9</fullName>
                </value>
                <value>
                    <fullName>5.8 SP5</fullName>
                </value>
                <value>
                    <fullName>5.8 SP4</fullName>
                </value>
                <value>
                    <fullName>5.8 SP3</fullName>
                </value>
                <value>
                    <fullName>5.8 SP2</fullName>
                </value>
                <value>
                    <fullName>5.8 SP1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CaseControllerExtension.cls
public with sharing class CaseControllerExtension {

    public string caseNumber{get; set;}
    public string contactName{get; set;}
    public string recordTypeName{get; set;}
    
    private final case cs;  

    
    public CaseControllerExtension(ApexPages.StandardController stdController){
        this.cs = (case)stdController.getRecord();
        setContractProperties();
        setCaseNumber();
        setContactName();
    }
    
    private void setContractProperties(){
        cs.SCID__c = ApexPages.currentPage().getParameters().get('00N56000000aq9v');
        cs.SCTY__c = ApexPages.currentPage().getParameters().get('00N56000000aqLc');
        
        if(cs.SCID__c != null) {
            //Adding code for portal user
            ServiceContract svcContract = [SELECT Id, AccountId, Zuercher_Suite_Version__c, Account_Support_Team_WMP__c,Contract_Type__c FROM ServiceContract WHERE Id = :cs.SCID__c];
            ID rtIdZ = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Zuercher Customer Support Ticket').getRecordTypeId();
            ID rtIdT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Support Ticket').getRecordTypeId();
            ID rtFO = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Cross Support Ticket').getRecordTypeId();
            
            if(((svcContract.Account_Support_Team_WMP__c == 'Zuercher')||(svcContract.Account_Support_Team_WMP__c == 'LETG')||(svcContract.Account_Support_Team_WMP__c == 'ETI')||(svcContract.Account_Support_Team_WMP__c == 'Impact'))&& svcContract.Contract_Type__c != 'Field Ops') {
            	cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Zuercher Customer Support Ticket').getRecordTypeId();
            	recordTypeName = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Zuercher Customer Support Ticket').getName();
            	cs.Reported_Major_Version_WMP__c = svcContract.Zuercher_Suite_Version__c;
            }
            if(((svcContract.Account_Support_Team_WMP__c != 'Zuercher')&&(svcContract.Account_Support_Team_WMP__c != 'LETG')&&(svcContract.Account_Support_Team_WMP__c != 'ETI')&&(svcContract.Account_Support_Team_WMP__c != 'Impact'))&& svcContract.Contract_Type__c != 'Field Ops') {
                cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Support Ticket').getRecordTypeId();
                recordTypeName = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Support Ticket').getName();
            }
            if(svcContract.Contract_Type__c == 'Field Ops') {
                cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Cross Support Ticket').getRecordTypeId();
                recordTypeName = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Cross Support Ticket').getName();
            }
            //End of Adding code for portal user
        } else {
            recordTypeName = [Select Id, Name from RecordType where Id =: this.cs.RecordTypeId].Name;
        }
        
	
        //cs.Contact = cs.Contact == null?new Contact(Id=Id.valueOf(ApexPages.currentPage().getParameters().get('cas3_lkid'))):cs.Contact;
        cs.Origin = 'Customer Portal';
    }
    
    private void setCaseNumber(){
        caseNumber = cs.CaseNumber == null? 'Pending' : cs.CaseNumber;
    }
    
    private void setContactName(){
        contactName = cs.Contact.Name == null ? UserInfo.getName() : cs.Contact.Name;
	        System.debug('cs****'+cs);
    }
}