src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Contact_Date_Time_WMP__c</fullName>
        <label>Customer Contact Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Occured_After_Upgrade_WMP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Occurred After Upgrade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reported_Major_Version_WMP__c</fullName>
        <inlineHelpText>Choose your TriTech Software Version</inlineHelpText>
        <label>Reported Major Version</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undecided</fullName>
                </value>
                <value>
                    <fullName>7.10</fullName>
                </value>
                <value>
                    <fullName>7.9 SP1</fullName>
                </value>
                <value>
                    <fullName>7.0</fullName>
                </value>
                <value>
                    <fullName>6.7</fullName>
                </value>
                <value>
                    <fullName>6.6</fullName>
                </value>
                <value>
                    <fullName>6.5</fullName>
                </value>
                <value>
                    <fullName>6.4 SP5</fullName>
                </value>
                <value>
                    <fullName>6.4.SP4</fullName>
                    <label>6.4 SP4</label>
                </value>
                <value>
                    <fullName>6.4.SP3</fullName>
                    <label>6.4 SP3</label>
                </value>
                <value>
                    <fullName>6.4.SP2</fullName>
                    <label>6.4 SP2</label>
                </value>
                <value>
                    <fullName>6.4.SP1</fullName>
                </value>
                <value>
                    <fullName>6.4</fullName>
                </value>
                <value>
                    <fullName>6.3</fullName>
                </value>
                <value>
                    <fullName>6.2</fullName>
                </value>
                <value>
                    <fullName>6.1</fullName>
                </value>
                <value>
                    <fullName>6.0</fullName>
                </value>
                <value>
                    <fullName>5.15</fullName>
                </value>
                <value>
                    <fullName>5.14</fullName>
                </value>
                <value>
                    <fullName>5.13</fullName>
                </value>
                <value>
                    <fullName>5.12</fullName>
                </value>
                <value>
                    <fullName>5.11 SP2</fullName>
                </value>
                <value>
                    <fullName>5.11 SP1</fullName>
                </value>
                <value>
                    <fullName>5.11</fullName>
                </value>
                <value>
                    <fullName>5.10 SP1</fullName>
                </value>
                <value>
                    <fullName>5.10</fullName>
                </value>
                <value>
                    <fullName>5.9 SP1</fullName>
                </value>
                <value>
                    <fullName>5.9</fullName>
                </value>
                <value>
                    <fullName>5.8 SP13</fullName>
                </value>
                <value>
                    <fullName>5.8 SP12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Issue_Summary_WMP__c</fullName>
        <label>Short Issue Summary</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Supportable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Support Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestTicketViewController.cls
// ==================================================================================
//   Object: TestTicketViewController
//  Company: Tritech
//   Author: Mohan Kumar (Sales Optimizer)
// Comments: Testing of TicketViewController class..
// ==================================================================================
//  Changes: 2012-11-20 Initial version.
// ==================================================================================

@isTest
private class TestTicketViewController {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        RecordType rType = [Select r.SobjectType, r.Name, r.Id From RecordType r Where r.SobjectType='Case' and r.Name = 'Customer Support Ticket' limit 1];
        Case cse = new Case();
    
        //Product2 prdct = [SELECT Id, Name FROM Product2 LIMIT 1];
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.Family = 'Findit';
        p.IsActive = true;
        p.ProductCode = 'TestCode';
        p.Supportable__c = true;
        insert p;
            
        cse.ProductId = p.Id;
        cse.Short_Issue_Summary_WMP__c = 'Error when creating new product';
        cse.Priority = 'P2';
        cse.Subject = 'Issue with new product';
        cse.Occured_After_Upgrade_WMP__c = true;
        cse.Reported_Major_Version_WMP__c = '5.9';
        cse.Status = 'Closed';
        cse.RecordTypeId = rType.Id;
        cse.Customer_Contact_Date_Time_WMP__c = System.now();
        
        insert cse;
        
        TicketViewController tv = new TicketViewController(new apexpages.Standardcontroller(cse));
        tv.autoRun();
        tv.autoRunToClose();
    }
}