src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>After_Hours_Contact_WMP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Designated after hours contact for 24/7 support issues</inlineHelpText>
        <label>After Hours Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSC_Portal_Access_Request__c</fullName>
        <inlineHelpText>Please choose the appropriate access level for the contact.</inlineHelpText>
        <label>CSC Portal Access Request:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager (Tickets Creation/Edits, Contacts, Reports, Knowledge Base)</fullName>
                </value>
                <value>
                    <fullName>Standard (Ticket Creation/Edits, Knowledge Base)</fullName>
                </value>
                <value>
                    <fullName>Read Only (Knowledge Base read only)</fullName>
                </value>
                <value>
                    <fullName>Read Only with Tickets (Knowledge Base and Tickets read only)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inactive_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_Sales_Promos_Training__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - Sales Promos/Training</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionCAD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionCAD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionFBR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionFBR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionFIRE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionFIRE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionFORCE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionFORCE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionINFORM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionINFORM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionJAIL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionJAIL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionLMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionLMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionMOBILE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionMOBILE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptIn_VisionRMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xOpt In - VisionRMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_WMP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_WMP__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorized User</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Customer Staff</fullName>
                </value>
                <value>
                    <fullName>Director/Chief/Owner</fullName>
                </value>
                <value>
                    <fullName>Expungement Authorized</fullName>
                </value>
                <value>
                    <fullName>GIS Contact</fullName>
                </value>
                <value>
                    <fullName>IT Contact</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Contact</fullName>
                </value>
                <value>
                    <fullName>Upgrade Contact</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactViewController.cls
// ==================================================================================
//   Object: ContactViewController
//  Company: Tritech
//   Author: Mohan Kumar (Sales Optimizer)
// Comments: Created a custom view page for the portal users to remove the account name from the layout.
// ==================================================================================
//  Changes: 2012-12-01 Initial version.
// ==================================================================================

public with sharing class ContactViewController {
	public Contact cont {get;set;}
	public String contId {get;set;}
	public String address {get;set;}
	
	public ContactViewController(Apexpages.Standardcontroller sc) {
		contId = sc.getId();
		cont = new Contact();
		cont = [Select Id, Name, Title, Role_WMP__c, Primary_Contact_WMP__c, Phone, OptIn_VisionRMS__c, OptIn_VisionMOBILE__c, 
					OptIn_VisionLMS__c, OptIn_VisionJAIL__c, OptIn_VisionINFORM__c, OptIn_VisionFORCE__c, OptIn_VisionFIRE__c, 
					OptIn_VisionFBR__c, OptIn_VisionCAD__c, OptIn_Sales_Promos_Training__c, MobilePhone, MailingStreet, MailingState, 
					MailingPostalCode, MailingCountry, MailingCity, Inactive_Contact__c, HomePhone, Fax, Email, 
					CSC_Portal_Access_Request__c, After_Hours_Contact_WMP__c, HasOptedOutOfEmail 
				From Contact Where Id =: contId];
		if(cont.MailingStreet != null) {
			address = cont.MailingStreet + '</br>';
		}
		if(cont.MailingCity != null) {
			address += cont.MailingCity;
		}
		if(cont.MailingState != null) {
			if(cont.MailingCity != null) {
				address += ', ';
			}
			address += cont.MailingState;
		}
		if(cont.MailingPostalCode != null) {
			address += ' ' + cont.MailingPostalCode;
		}
		if(cont.MailingCountry != null) {
			address += '</br>' + cont.MailingCountry;
		}
	}
	public Pagereference autoRun() {
		List<User> userList = [Select u.Name, u.IsPortalEnabled, u.ContactId From User u Where IsPortalEnabled = true and Id =: Userinfo.getUserId()];
		if(userList.size() > 0) {
			return null;
		}
		return new Pagereference('/' + contId + '?nooverride=1');
	}
	
	public Pagereference editContact() {
		//return new Pagereference('/' + contId + '/e?clone=1&retURL=/' + contId);
		return new Pagereference('/apex/ContactEdit?id=' + contId + '&retURL=/' + contId);
	}
	
	public Pagereference cloneContact() {
		//return new Pagereference('/' + contId + '/e?clone=1&retURL=/' + contId);
		return new Pagereference('/apex/ContactEdit?id=' + contId + '&clone=1&retURL=/' + contId);
	}
}