src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Unsubscribe_Email_Digest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unsubscribe Email Digest?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email_Digest_Log__c.object
<CustomObject>
    <description>Object for sending/tracking weekly RoundTable emails sent to customer portal users based on their specific RoundTable needs.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Digest Logs</relationshipLabel>
        <relationshipName>Email_Digest_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Address__c</fullName>
        <label>To Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>Respond</fullName>
                </value>
                <value>
                    <fullName>Perform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Digest Log</label>
    <nameField>
        <displayFormat>Digest-{0000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Digest Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>IQ</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchIdeasReport.cls
global class BatchIdeasReport implements Database.Batchable<SObject>, Database.AllowsCallouts{
      
    global database.Querylocator start(Database.BatchableContext BC){
        if(Test.isRunningTest()){
            
            return Database.getQueryLocator([Select u.IsPortalEnabled, u.IsActive, u.Email, u.ContactId, u.Contact.AccountId From User u Where UserName like 'testBatchIdeasReport%' Limit 1]);
        }
         
        return Database.getQueryLocator([Select u.IsPortalEnabled, u.IsActive, u.Email, u.ContactId, u.Contact.AccountId From User u 
        								Where u.IsPortalEnabled = true AND u.IsActive = true AND Contact.Unsubscribe_Email_Digest__c != true]);
    }
  
    global void execute(Database.BatchableContext BC,Sobject[] scope){
        
      try{
        
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
         
        List<Email_Digest_Log__c> listEmailLog = new List<Email_Digest_Log__c>();
          
        for(sobject s : scope){
        	User portalUser = (User)s;
            
            
	            boolean isRespond = false;
	            boolean isInform = false;
	            boolean isPerform = false;
	            boolean isTiburon = false;
	            
	            for(ServiceContract sc : [Select Id,Product_Family_WMP__c From ServiceContract Where AccountId = : portalUser.Contact.AccountId  ]){
	            	
	            	
	            	if(sc.Product_Family_WMP__c == 'Inform' || sc.Product_Family_WMP__c == 'VisiNet' || sc.Product_Family_WMP__c == 'VisionAIR' || sc.Product_Family_WMP__c == '911'){
	            		isInform = true;
	            	}
	            	
	            	if(sc.Product_Family_WMP__c == 'EMS' || sc.Product_Family_WMP__c == 'Respond (EMS)' || sc.Product_Family_WMP__c == 'Respond'){
	            		isRespond = true;
	            	}
	            	
	            	if(sc.Product_Family_WMP__c == 'IMC'){
	            		isPerform = true;
	            	}
	            	
	            	if(sc.Product_Family_WMP__c == 'Tiburon'){
	            		isTiburon = true;
	            	}
	            	
	            }
	             
	            if(isInform == true){
		            string htmlBody = IdeasReportEmailDigest.getInformEmailBody(portalUser.ContactId);
		             
		            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		            
		            //List<String> toAddressList = new List<String>();  
		            //toAddressList.add('yogesh.rankawat@gmail.com'); 
		            //mail.setToAddresses(toAddressList); 
		            
		            mail.setTargetObjectId(portalUser.Id);
		            mail.setSaveAsActivity(false);
		            
		            mail.setSubject('TriTech RoundTable Weekly Report');
		            mail.setHtmlBody(htmlBody);
		            
		            mail.setSenderDisplayName('Tritech RoundTable');
		            mail.setReplyTo('jen.vansant@tritech.com');
		            
		            emails.add(mail);
		            
		            // Email Log
		            Email_Digest_Log__c emailLog = new Email_Digest_Log__c();
		            emailLog.Contact__c = portalUser.ContactId;
		            emailLog.Type__c = 'Inform';
		            emailLog.To_Address__c = portalUser.Email;
		            emailLog.Email_Subject__c = 'TriTech RoundTable Weekly Report';
		            emailLog.Email_Body__c = htmlBody;
		            listEmailLog.add(emailLog);
	            }
	             
	            if(isRespond == true){
		            string htmlBody = IdeasReportEmailDigest.getRespondEmailBody(portalUser.ContactId);
		             
		            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		            
		            //List<String> toAddressList = new List<String>();  
		            //toAddressList.add('yogesh.rankawat@gmail.com'); 
		            //mail.setToAddresses(toAddressList);
		            
		            mail.setTargetObjectId(portalUser.Id);
		            mail.setSaveAsActivity(false);
		            
		            mail.setSubject('TriTech RoundTable Weekly Report');
		            mail.setHtmlBody(htmlBody);
		            
		            mail.setSenderDisplayName('Tritech RoundTable');
		            mail.setReplyTo('jen.vansant@tritech.com');
		            
		            emails.add(mail);
		             
		            // Email Log
		            Email_Digest_Log__c emailLog = new Email_Digest_Log__c();
		            emailLog.Contact__c = portalUser.ContactId;
		            emailLog.Type__c = 'Respond';
		            emailLog.To_Address__c = portalUser.Email;
		            emailLog.Email_Subject__c = 'TriTech RoundTable Weekly Report';
		            emailLog.Email_Body__c = htmlBody;
		            listEmailLog.add(emailLog);
	            }
	            
	            if(isPerform == true){
		            string htmlBody = IdeasReportEmailDigest.getPerformEmailBody(portalUser.ContactId);
		             
		            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		            
		            //List<String> toAddressList = new List<String>(); 
		            //toAddressList.add('yogesh.rankawat@gmail.com'); 
		            //mail.setToAddresses(toAddressList);
		            
		            mail.setTargetObjectId(portalUser.Id);
		            mail.setSaveAsActivity(false);
		            
		            mail.setSubject('TriTech RoundTable Weekly Report');
		            mail.setHtmlBody(htmlBody);
		            
		            mail.setSenderDisplayName('Tritech RoundTable');
		            mail.setReplyTo('jen.vansant@tritech.com');
		            
		            emails.add(mail);
		            
		            // Email Log
		            Email_Digest_Log__c emailLog = new Email_Digest_Log__c();
		            emailLog.Contact__c = portalUser.ContactId;
		            emailLog.Type__c = 'Perform';
		            emailLog.To_Address__c = portalUser.Email;
		            emailLog.Email_Subject__c = 'TriTech RoundTable Weekly Report';
		            emailLog.Email_Body__c = htmlBody;
		            listEmailLog.add(emailLog);
	            }
	            
	            if(isTiburon == true) {
	            	
		            string htmlBody = IdeasReportEmailDigest.getTiburonEmailBody(portalUser.ContactId);
		             
		            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		            
		            //List<String> toAddressList = new List<String>(); 
		            //toAddressList.add('yogesh.rankawat@gmail.com'); 
		            //mail.setToAddresses(toAddressList);
		            
		            mail.setTargetObjectId(portalUser.Id);
		            mail.setSaveAsActivity(false);
		            
		            mail.setSubject('TriTech RoundTable Weekly Report');
		            mail.setHtmlBody(htmlBody);
		            
		            mail.setSenderDisplayName('Tritech RoundTable');
		            mail.setReplyTo('jen.vansant@tritech.com');
		            
		            emails.add(mail);
		            
		            // Email Log
		            Email_Digest_Log__c emailLog = new Email_Digest_Log__c();
		            emailLog.Contact__c = portalUser.ContactId;
		            emailLog.Type__c = 'Tiburon';
		            emailLog.To_Address__c = portalUser.Email;
		            emailLog.Email_Subject__c = 'TriTech RoundTable Weekly Report';
		            emailLog.Email_Body__c = htmlBody;
		            listEmailLog.add(emailLog);
	            
	            }
             
	    }
	     
	    if(emails.size() > 0){
	    	
        	List<Messaging.Sendemailresult> results = Messaging.sendEmail(emails , true);
        	
        	if(listEmailLog.size() > 0){
        		
        		insert listEmailLog;
        	}
        }
	    
      }
      catch(Exception ex){
        system.debug(ex.getMessage());
      } 
      
    }
  
    global void finish(Database.BatchableContext BC){

    }
}