src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Contract</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Contract Amendment</fullName>
                </value>
                <value>
                    <fullName>Sales Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
                <value>
                    <fullName>IMC</fullName>
                    <color>#78C953</color>
                    <label>IMC</label>
                </value>
                <value>
                    <fullName>Inform 911</fullName>
                    <color>#F3D904</color>
                    <label>Inform 911</label>
                </value>
                <value>
                    <fullName>Inform CAD</fullName>
                    <color>#F3D904</color>
                    <label>Inform CAD</label>
                </value>
                <value>
                    <fullName>Inform FBR</fullName>
                    <color>#F3D904</color>
                    <label>Inform FBR</label>
                </value>
                <value>
                    <fullName>Inform FBR Custom Solution</fullName>
                    <color>#F3D904</color>
                    <label>Inform FBR Custom Solution</label>
                </value>
                <value>
                    <fullName>Inform IQ</fullName>
                    <color>#F3D904</color>
                    <label>Inform IQ</label>
                </value>
                <value>
                    <fullName>Inform Jail</fullName>
                    <color>#F3D904</color>
                    <label>Inform Jail</label>
                </value>
                <value>
                    <fullName>Inform Mobile</fullName>
                    <color>#F3D904</color>
                    <label>Inform Mobile</label>
                </value>
                <value>
                    <fullName>Inform RMS</fullName>
                    <color>#F3D904</color>
                    <label>Inform RMS</label>
                </value>
                <value>
                    <fullName>Inform RMS Custom Solution</fullName>
                    <color>#F3D904</color>
                    <label>Inform RMS Custom Solution</label>
                </value>
                <value>
                    <fullName>Respond Billing</fullName>
                    <color>#0B6FCE</color>
                    <label>Respond Billing</label>
                </value>
                <value>
                    <fullName>Respond CAD</fullName>
                    <color>#0B6FCE</color>
                    <label>Respond CAD</label>
                </value>
                <value>
                    <fullName>Respond ePCR</fullName>
                    <color>#0B6FCE</color>
                    <label>Respond ePCR</label>
                </value>
                <value>
                    <fullName>SBS</fullName>
                    <color>#0B6FCE</color>
                    <label>SBS</label>
                </value>
                <value>
                    <fullName>Sweet CAD</fullName>
                    <color>#0B6FCE</color>
                    <label>Sweet CAD</label>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>TriTech.com Analytics</fullName>
                    <color>#F3D904</color>
                    <label>TriTech.com Analytics</label>
                </value>
                <value>
                    <fullName>TriTech.com Billing</fullName>
                    <color>#0B6FCE</color>
                    <label>TriTech.com Billing</label>
                </value>
                <value>
                    <fullName>TriTech.com ePCR</fullName>
                    <color>#0B6FCE</color>
                    <label>TriTech.com ePCR</label>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                    <color>#F3D904</color>
                    <label>VisiNet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>IQ</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/hideTabController_CP.cls
global class hideTabController_CP
{
    webservice static List<boolean> hideTabMethod_CP()
    {
        List<boolean> showTabLst = new List<boolean>();
        boolean showResourceTab = false;
        boolean showDocumentTab = false;
        boolean showIMCTab = false;
        Boolean showRoundTableTab = true;
        
        string userId = UserInfo.getUserId();
        User u = [select Id, AccountID,ContactId from User where Id =:userId];
        
        //Mohan 05/02/2014
        //Adding new contract types Inform 911, Inform CAD, Inform FBR, Inform Jail, Inform Mobile, Inform RMS 
        //Mohan 05/02/2014: Adding new contract types - Inform IQ, Inform Anaytics
        //Mohan 06/25/2014: Adding new contract types - Tritech.com IQ, TriTech.com Analytics, Third Party, Geo Comm
        //removed Inform Contract types as we do not want the EMS tab displayed for Inform. SK
        //Mohan 02/20/2015: Adding new filter Product_Family_WMP__c = 'EMS' so that the EMS tab is not visible for other product families
        
        //List<string> contractType = new List<string>{'Billing','EMS CAD','FDC','Fusion ePCR','Fusion Online','SBS','Sweet-Online','AVeL','TriTech.com ePCR','TriTech.com Billing','Respond Billing','Respond ePCR', 'Sweet CAD', 'Respond CAD', 'Inform 911', 'Inform CAD', 'Inform FBR', 'Inform Jail', 'Inform Mobile', 'Inform RMS', 'Inform IQ', 'Inform Anaytics', 'Tritech.com IQ', 'TriTech.com Analytics', 'Third Party', 'Geo Comm',' Inform CAD Custom Solution',' Inform Mobile Custom Solution','Inform RMS Custom Solution','Inform FBR Custom Solution'};
        List<string> contractType = new List<string>{'Billing','EMS CAD','FDC','Fusion ePCR','Fusion Online','SBS','Sweet-Online','AVeL','TriTech.com ePCR','TriTech.com Billing','Respond Billing','Respond ePCR', 'Sweet CAD', 'Respond CAD', 'Tritech.com IQ', 'TriTech.com Analytics', 'Third Party', 'Geo Comm'};
        List<ServiceContract> scList = new List<ServiceContract>();
        scList = [Select Id, Contract_Status_WMP__c, Contract_Type__c from ServiceContract where AccountId =:u.AccountId AND (Contract_Status_WMP__c = 'Active' OR Contract_Status_WMP__c = 'Renewal Due' OR Contract_Status_WMP__c = 'No HW Support, Software Only') AND Contract_Type__c in: contractType AND Product_Family_WMP__c = 'EMS'];      
        System.debug('size::' + scList.size());
        if(scList.size() > 0)
             showResourceTab = true;
             
        List<ServiceContract> scListIMC = new List<ServiceContract>();
        List<ServiceContract> scListVisinet = new List<ServiceContract>();
        List<ServiceContract> scListAll = [Select Id, Contract_Status_WMP__c, Contract_Type__c,Product_Family_WMP__c from ServiceContract where AccountId =:u.AccountId AND (Contract_Status_WMP__c = 'Active' OR Contract_Status_WMP__c = 'Installed Not Live' OR Contract_Status_WMP__c = 'Renewal Due' OR Contract_Status_WMP__c = 'No HW Support, Software Only') AND (Product_Family_WMP__c = 'VisiNet' OR Product_Family_WMP__c = 'IMC' OR Product_Family_WMP__c = 'Inform')];
        String pFamilies = '';
        for(ServiceContract sc:scListAll)
        {
            if((sc.Product_Family_WMP__c == 'VisiNet') || (sc.Product_Family_WMP__c == 'Inform'))
            {
                scListVisinet.add(sc);
            }
            if(sc.Product_Family_WMP__c == 'IMC')
            {
                scListIMC.add(sc);
            }
            //pFamilies += sc.Product_Family_WMP__c + ',';        //remove when Perform category goes live for Round table 
        }
        
        if(scListVisinet.size() > 0)
             showDocumentTab = true;
        if(scListIMC.size() > 0)
             showIMCTab = true;
        
        
        showTabLst.add(showResourceTab);        
        showTabLst.add(showDocumentTab);
        showTabLst.add(showIMCTab);
        //showTabLst.add(showRoundTableTab);//remove when Perform category goes live for Round table
        
        return showTabLst;
    }
    static testMethod void unitTest() 
    {
        User u1 = [Select Id, AccountId from User where IsPortalEnabled = true and IsActive = true LIMIT 1];
        List<ServiceContract> scList = new List<ServiceContract>();
        ServiceContract sc1 = new ServiceContract(Name = 'SC1',Contract_Type__c = 'EMS', Contract_Status_WMP__c = 'Active', AccountId = u1.AccountId);
        scList.add(sc1);
        ServiceContract sc2 = new ServiceContract(Name = 'SC2',Product_Family_WMP__c = 'VisiNet',Contract_Status_WMP__c = 'Active', AccountId = u1.AccountId);
        scList.add(sc2);
        ServiceContract sc5 = new ServiceContract(Name = 'SC2',Product_Family_WMP__c = 'Inform',Contract_Status_WMP__c = 'Active', AccountId = u1.AccountId);
        scList.add(sc5);
        ServiceContract sc3 = new ServiceContract(Name = 'SC3',Product_Family_WMP__c = 'IMC',Contract_Status_WMP__c = 'Active', AccountId = u1.AccountId);
        scList.add(sc3);
        ServiceContract sc4 = new ServiceContract(Name = 'SC1',Contract_Type__c = 'FDC', Contract_Status_WMP__c = 'Active', AccountId = u1.AccountId);
        scList.add(sc4);
        insert scList;
        
        System.runAs(u1){
            hideTabController_CP.hideTabMethod_CP();
        }
    }
}