src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booked_Value__c</fullName>
        <label>Booked Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Click the icon to associate a contact from this account to the opportunity</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_TriTech_Lost__c</fullName>
        <label>Reason TriTech Lost</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Feature/Function</fullName>
                </value>
                <value>
                    <fullName>References</fullName>
                </value>
                <value>
                    <fullName>Out-Sold</fullName>
                </value>
                <value>
                    <fullName>Lack of PreSales</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Write_In__c.object
<CustomObject>
    <description>Object used for creating write-in quote generation in conjunction with Quote</description>
    <fields>
        <fullName>CWI_Status__c</fullName>
        <label>CWI Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Information</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Approved - Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Custom Write-Ins</relationshipLabel>
        <relationshipName>Work_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>Total Command</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>DispatchNow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TriTech_Product_Version__c</fullName>
        <inlineHelpText>Product version currently installed or to be installed</inlineHelpText>
        <label>TriTech Product Version</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Write-In</label>
    <nameField>
        <displayFormat>CWI-{00000000}</displayFormat>
        <label>Custom Write-In</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Write-In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCWICancellation.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestCWICancellation {

    static testMethod void myUnitTest() {
        
    Account acc = new Account();
      acc.Name = 'WO test';
      //acc.RecordTypeId = rt.Id;
      insert acc;
      
   contact cont = new contact();
   cont.lastname = 'Brown';
   insert cont;
   
   Opportunity opp = new Opportunity();
        opp.name = 'Opp Test';
        opp.AccountID = acc.id;
        opp.CloseDate = System.Today();
        opp.StageName = 'Opportunity Identified';
        opp.Contact__c = cont.id;
        insert opp;
    
    Write_In__c WI = new Write_In__c();
        WI.Opportunity__c = opp.id;        
        WI.CWI_Status__c = 'Draft';
        WI.Product_Line__c = 'Inform';
        WI.TriTech_Product_Version__c = '10';
        insert WI;
    
    opp.StageName = 'Closed Lost';
    opp.CloseDate = System.Today();
    opp.Reason_TriTech_Lost__c = 'Price';
    upsert opp;  
    
    opp.StageName = 'Booked';
    opp.CloseDate = System.Today();
    opp.booked_value__c = 100.00;
    upsert opp;    
    }
}