src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Click the icon to associate a contact from this account to the opportunity</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products_Required__c</fullName>
        <inlineHelpText>For Inform quotes, please choose all products that apply to this Opportunity</inlineHelpText>
        <label>Product(s) Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>911 Consulting</fullName>
                </value>
                <value>
                    <fullName>Accident Reporting (Extend)</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Data Vault</fullName>
                </value>
                <value>
                    <fullName>DispatchNow</fullName>
                </value>
                <value>
                    <fullName>eCitations (Extend)</fullName>
                </value>
                <value>
                    <fullName>FBR</fullName>
                </value>
                <value>
                    <fullName>FBR (Extend)</fullName>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Fire Records</fullName>
                </value>
                <value>
                    <fullName>GIS Services</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Insight AVL</fullName>
                </value>
                <value>
                    <fullName>Insight Dispatch</fullName>
                </value>
                <value>
                    <fullName>Insight Mobile</fullName>
                </value>
                <value>
                    <fullName>IQ/Analytics</fullName>
                </value>
                <value>
                    <fullName>IQResponse</fullName>
                </value>
                <value>
                    <fullName>Jail</fullName>
                </value>
                <value>
                    <fullName>Jail Extend</fullName>
                </value>
                <value>
                    <fullName>LETG Add On</fullName>
                </value>
                <value>
                    <fullName>LETG eCitations</fullName>
                </value>
                <value>
                    <fullName>Mapping (Zuercher)</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Municipal Courts</fullName>
                </value>
                <value>
                    <fullName>RMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <description>If quote number is Null, then workflow &quot;Set Quote #&quot; will populate it with the CPQ Quote Number value.  This will accommodate both legacy quote number entries and new CPQ quote number entries.</description>
        <label>Quote Number</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SalesOrderTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SalesOrderTestClass {

    static testMethod void SalesOrderTest() {
    Account testAccount = new Account();
    testAccount.Name='Visinet Test Account';
    insert testAccount;	
    
    Contact cont = new Contact();
    cont.FirstName='Jen';
    cont.LastName='Vansant';
    cont.Accountid=testAccount.id;
    insert cont;
    	
    opportunity opp = new opportunity(name='Visinet Test',
    	Account=testAccount,
    	Contact__c=cont.id,
    	Products_Required__c='RMS',
    	CloseDate=System.today(),
    	Quote_Number__c='QUO-12345-abcd',
    	RecordTypeID='0124D0000008jfP',
    	Description='Executive Summary',
    	StageName='Selected',
    	Probability=95);
    insert opp;	 
        
    }
}