src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Bookings_Date__c</fullName>
        <label>Bookings Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GP_Customer_ID__c</fullName>
        <label>GP Customer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inform_Bookings_Amount__c</fullName>
        <label>Inform Bookings Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <formula>Related_Opportunity__r.Opportunity_Owner_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <label>Quote Number - Click to View Sales Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Log</label>
    <nameField>
        <label>Sales Order Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesOrderCont.cls
//Class to gather data for Sales Order Log Excel output
//written by Scott Key
//8-17-2017

public class SalesOrderCont {
	public Transient List<Sales_Order__c> soc{get; set;}
	public string quote {get; set;}
    public SalesOrderCont()
    {
      	soc = new List<Sales_Order__c>();
      	for (Sales_Order__c c : [Select Quote_Number__c,Sales_Order_Number__c,Name,Bookings_Date__c,client__c,GP_Customer_ID__c,Opportunity_Owner__c,
      		Inform_Bookings_Amount__c,Related_Opportunity__c from Sales_Order__c where Bookings_Date__c = THIS_YEAR order by Bookings_Date__c desc])
    	{
    		soc.add(c);
    	}
    }
    public SalesOrderCont(ApexPages.StandardController stdController)
    {
    	
    }
    
     public PageReference redirectcurrent()
    {
        PageReference pr1 = new PageReference('/apex/scottExcellTest2');
        return pr1;
    }
    public PageReference redirectlast()
    {
        PageReference pr2 = new PageReference('/apex/salesorderloglastyear');
        return pr2;
    }
   
    public PageReference searchSalesOrders()
    {
    	soc = [select Quote_Number__c,Sales_Order_Number__c,Name,Bookings_Date__c,client__c,GP_Customer_ID__c,Opportunity_Owner__c,
      		Inform_Bookings_Amount__c,Related_Opportunity__c from sales_Order__c where quote_number__c = :quote];
    	return null;
    }
}