src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Bonds__c</fullName>
        <label>Bonds</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bookings_Date__c</fullName>
        <label>Bookings Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CAD_Software_List__c</fullName>
        <label>CAD Software List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSL__c</fullName>
        <label>CSL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Order_Number__c</fullName>
        <label>Change Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datavault_List__c</fullName>
        <label>Datavault List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Director__c</fullName>
        <formula>Related_Opportunity__r.Owner.Manager.FirstName + &apos; &apos; + Related_Opportunity__r.Owner.Manager.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Other__c</fullName>
        <label>Discount Other</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Escrow__c</fullName>
        <label>Escrow</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FBR_List__c</fullName>
        <label>FBR List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fire_List__c</fullName>
        <label>Fire List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GP_Customer_ID__c</fullName>
        <label>GP Customer ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>G_or_C__c</fullName>
        <label>G or C</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HW_3rd_Paty_List__c</fullName>
        <formula>Hardware_List__c +  Hardware_Support_List__c + X3rd_Party_Soft_List__c +  Subcontract_List__c +  Subcontract_Support_List__c +  Datavault_List__c +  SI_List__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HW 3rd Party List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HW_3rd_party_SW_Subtotal__c</fullName>
        <formula>Hardware_3rd_Party__c +  Hardware_3rd_Party_Support__c +  X3rd_Party_Software__c +  X3rd_Party_Support__c +  Subcontract__c +  Subcontract_Support__c +  Datavault_Subscription__c +  System_Integration__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HW, 3rd party SW Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hardware_3rd_party_Discount__c</fullName>
        <formula>HW_3rd_Paty_List__c -  HW_3rd_party_SW_Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hardware/3rd Party Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hardware_List__c</fullName>
        <label>Hardware List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hardware_Support_List__c</fullName>
        <label>Hardware Support List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IQ_List__c</fullName>
        <label>IQ List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IS_Services_List__c</fullName>
        <label>IS Services List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inform_Bookings_Amount__c</fullName>
        <label>Inform Bookings Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interface_CAD_Mobile_Software__c</fullName>
        <label>Interface CAD/Mobile Software</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interface_RMS_FBR_Jail_Software__c</fullName>
        <label>Interface RMS/FBR/Jail Software</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jail_List__c</fullName>
        <label>Jail List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mobile_List__c</fullName>
        <label>Mobile List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>N_E__c</fullName>
        <label>N/E</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Deferred_Rev__c</fullName>
        <label>Other Deferred Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Services__c</fullName>
        <label>Other Services</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Services__c</fullName>
        <formula>((  CAD_Software__c +  FBR_Software__c +  Interface_CAD_Mobile_Software__c +  Interface_RMS_FBR_Jail_Software__c +  Fire_Software__c +  IQ_Licenses__c +  Jail_Software__c +  Mobile_Software__c +  RMS_Software__c +  Telephony_911__c +  Subscp_RMS_FBR__c +  Software_Subscription_On_Prem__c  +  PandI_Services__c +  IS_Services__c +  Training_Services__c +  Other_Services__c ) * 14)/100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PM Services</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P_I_List__c</fullName>
        <label>P&amp;I List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prepain_maintenance_Pool__c</fullName>
        <label>Prepaid Maintenance Pool</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <label>Project Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <label>Quote Number - Click to View Sales Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMS_List__c</fullName>
        <label>RMS List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <label>Sales Rep</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services_Discount__c</fullName>
        <formula>Services_List__c -  Services_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Services Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Services_List__c</fullName>
        <formula>P_I_List__c +  IS_Services_List__c +  Training_Services_List__c +  PM_Services__c + Other_Services__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Services List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Services_Total__c</fullName>
        <formula>PandI_Services__c +  IS_Services__c +  Training_Services__c + PM_Services__c + Other_Services__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Services Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shipping__c</fullName>
        <label>Shipping</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Software_Discounts__c</fullName>
        <label>Software Discounts</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Software_List__c</fullName>
        <formula>CAD_Software_List__c +  CAD_Interface_List__c +  RMS_Interface_List__c +  Mobile_List__c +  RMS_List__c +  FBR_List__c +  Fire_List__c +  Jail_List__c +  Subscription_List__c +  IQ_List__c +  Telephony_List__c + Subscription_List__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Software List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Software_Subscription_On_Prem__c</fullName>
        <label>Software Subscription (On Prem)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Software_Support__c</fullName>
        <label>Software Support</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Software_Total__c</fullName>
        <formula>Software_List__c  -  Software_Discounts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Software Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcontract_List__c</fullName>
        <label>Subcontract  List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcontract_Support_List__c</fullName>
        <label>Subcontract Support List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_List__c</fullName>
        <label>Subscription List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Integration__c</fullName>
        <label>System Integration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>Related_Opportunity__r.Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Telephony_List__c</fullName>
        <label>Telephony List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Amount__c</fullName>
        <label>Total Contract Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Other__c</fullName>
        <formula>Shipping__c +  Escrow__c +  TriCon_Fees__c +  Bonds_L_C__c +  Travel_BAI__c +  Travel_Fixed__c +  Other__c +  Discount_Other__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Other</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Training_Services_List__c</fullName>
        <label>Training Services List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Travel_BAI__c</fullName>
        <label>Travel - BAI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Travel_Fixed__c</fullName>
        <label>Travel - Fixed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TriCon_Fees__c</fullName>
        <label>TriCON Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tritech_Com_Cont_2_Yrs_List__c</fullName>
        <label>TriTech.com Cont &gt; 2 Yrs List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tritech_Com_IQ_Hosting_List__c</fullName>
        <label>TriTech.com IQ Hosting List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tritech_Com_Install_List__c</fullName>
        <label>TriTech.com Install List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tritech_Com_Other_List__c</fullName>
        <label>TriTech.com Other List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Soft_List__c</fullName>
        <label>3rd Party Software List</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Support__c</fullName>
        <label>3rd Party Support</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Log</label>
    <nameField>
        <label>Sales Order Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Sales_Order_LogLY.cls
//Class to gather data for Sales Order Log Excel output
//written by Scott Key
//8-17-2017

public class Sales_Order_LogLY {
    public List<Sales_Order__c> soc{get; set;}
    public Sales_Order_LogLY()
    {
    Pagereference pr = null;	
    soc = new List<Sales_Order__c>();
       for (Sales_Order__c c : [Select Director__c, Quote_Number__c,Sales_Order_Number__c,Change_Order_Number__c,Client__c,GP_Customer_ID__c,Product_Type__c,N_E__c,
        G_or_C__c,Bookings_Date__c,Sales_Rep__c,CSL__c,Project_Manager__c,Inform_Bookings_Amount__c,Total_Contract_Amount__c,CAD_Software_List__c,Interface_CAD_Mobile_Software__c,
        Interface_RMS_FBR_Jail_Software__c,	Mobile_List__c,RMS_List__c,FBR_List__c,Jail_List__c,Fire_List__c,Software_Subscription_On_Prem__c,
        IQ_List__c,Telephony_List__c,Subscription_List__c,Software_List__c,Software_Discounts__c,Software_Total__c,P_I_List__c,IS_Services_List__c,Training_Services_List__c,
        PM_Services__c,Other_Services__c,Services_List__c,Services_Discount__c,Services_Total__c,Hardware_List__c,Hardware_Support_List__c,X3rd_Party_Soft_List__c,
        X3rd_Party_Support__c,Subcontract_List__c,Subcontract_Support_List__c,Datavault_List__c,System_Integration__c,HW_3rd_Paty_List__c,Hardware_3rd_party_Discount__c,
        HW_3rd_party_SW_Subtotal__c,Shipping__c,Escrow__c,TriCon_Fees__c,Bonds__c,Travel_Fixed__c,Travel_BAI__c,Other__c,Discount_Other__c,Total_Other__c,Software_Support__c,
        Prepain_maintenance_Pool__c,Tax__c,Other_Deferred_Rev__c,Tritech_Com_IQ_Hosting_List__c,Tritech_Com_Cont_2_Yrs_List__c,Tritech_Com_Other_List__c,Tritech_Com_Install_List__c,
        Tritech_Com_Training_List__c,Tritech_Com_Discount__c,Tritech_Com_List__c,Tritech_Com_Net__c,Retail__c,MO__c,ArcGIS_Run_Time__c,MO_Upgrade__c,NE__c,ArcGIS_Engine_10X__c,
        ArcGIS_Server_Network_Analyst__c,Dundas_Analytics__c,Possitive_Access__c,ESRI__c,Cost_Worksheet_Other__c,Total_Cost__c,Commissionable_Value__c,C_or_N__c from Sales_Order__c where Bookings_Date__c = Last_Year order by bookings_date__c])
       {       
           soc.add(c);
       }
    pr = new PageReference('/apex/SalesOrderLog?sfdc.tabName=01r4D0000008lED');
    pr.setRedirect(true);
    }
    public  Sales_Order_LogLY(ApexPages.StandardController stdController) {
    }
}