src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_WMP__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Inform</fullName>
                </value>
                <value>
                    <fullName>IQ</fullName>
                </value>
                <value>
                    <fullName>LETG</fullName>
                </value>
                <value>
                    <fullName>Tiburon</fullName>
                </value>
                <value>
                    <fullName>VisiNet</fullName>
                </value>
                <value>
                    <fullName>VisionAIR</fullName>
                </value>
                <value>
                    <fullName>Zuercher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchServiceContract.cls
global class BatchServiceContract implements Database.Batchable<SObject>, Database.AllowsCallouts{
      
    global database.Querylocator start(Database.BatchableContext BC){
    	Date dtEndDate = system.today().addDays(-91);
    	
        if(Test.isRunningTest()){
            
            return Database.getQueryLocator([Select Id,Product_Family_WMP__c,EndDate,Contract_Status_WMP__c From ServiceContract Limit 1]);
        }
         
        return Database.getQueryLocator([Select Id,Product_Family_WMP__c,EndDate,Contract_Status_WMP__c From ServiceContract Where EndDate >= : dtEndDate ]);
    }
  
    global void execute(Database.BatchableContext BC,Sobject[] scope){
        
      //try{
        
        List<ServiceContract> listSC = new List<ServiceContract>();
           
        for(sobject s : scope){
        	
        	ServiceContract serCont = (ServiceContract)s;
            
            //Service Contract: EMS
            
            if(serCont.Product_Family_WMP__c == 'EMS' && serCont.Contract_Status_WMP__c == 'Active' && serCont.EndDate == system.today().addDays(-1) ){ serCont.Contract_Status_WMP__c = 'Pending Renewal'; listSC.add(serCont); }
            
            
            //Service Contracts: 911 (Day 61)
            
            else if(serCont.Product_Family_WMP__c == '911' && (serCont.Contract_Status_WMP__c == 'No HW Support, Software Only' || serCont.Contract_Status_WMP__c == 'Active') 
            	&& serCont.EndDate == system.today().addDays(-61) ){ serCont.Contract_Status_WMP__c = 'Pending Renewal'; listSC.add(serCont); }
            
            
            //Service Contracts: 911 (Day 1 after End Date)
            
            else if(serCont.Product_Family_WMP__c == '911' && serCont.Contract_Status_WMP__c == 'Active' && serCont.EndDate == system.today().addDays(-1) ){ serCont.Contract_Status_WMP__c = 'No HW Support, Software Only'; listSC.add(serCont);}
            
            
            //Service Contracts: VisiNet IMC VisionAIR Inform (Day 1 after End Date)
            
            else if((serCont.Product_Family_WMP__c == 'Inform' || serCont.Product_Family_WMP__c == 'IMC' || serCont.Product_Family_WMP__c == 'VisiNet'  || serCont.Product_Family_WMP__c == 'VisionAIR')
            	 && serCont.Contract_Status_WMP__c == 'Active' && serCont.EndDate == system.today().addDays(-1) ){ serCont.Contract_Status_WMP__c = 'Renewal Due'; listSC.add(serCont); }
            
            
            //Service Contracts: VisiNet IMC VisionAIR Inform (Day 91 after End Date)
            
            else if((serCont.Product_Family_WMP__c == 'Inform' || serCont.Product_Family_WMP__c == 'IMC' || serCont.Product_Family_WMP__c == 'VisiNet'  || serCont.Product_Family_WMP__c == 'VisionAIR')
            	 && (serCont.Contract_Status_WMP__c == 'Active' || serCont.Contract_Status_WMP__c == 'Pending Renewal')  && serCont.EndDate == system.today().addDays(-91) ){ serCont.Contract_Status_WMP__c = 'Pending Renewal'; listSC.add(serCont);}
            
             
	    }
	    
	    if(listSC.size() > 0){ update listSC; }
	      
      //}
      //catch(Exception ex){
      //  system.debug(ex.getMessage());
      //} 
      
    }
  
    global void finish(Database.BatchableContext BC){

    }
}