src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status_WMP__c</fullName>
        <description>Pending Renewal = Inactive Status
Renewal Due = Active Status
No HW Support, Software Only = Active Status</description>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <color>#009900</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Emergency Support Only</fullName>
                    <color>#009900</color>
                    <label>Emergency Support Only</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#FF0000</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Installed Not Live</fullName>
                    <color>#009900</color>
                    <label>Installed Not Live</label>
                </value>
                <value>
                    <fullName>Sold but Not Installed</fullName>
                    <color>#FF0000</color>
                    <label>Sold but Not Installed</label>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#FF0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Vendor/Partner</fullName>
                    <color>#009900</color>
                    <label>Vendor/Partner</label>
                </value>
                <value>
                    <fullName>Inactive - Contract Expired</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Contract Expired</label>
                </value>
                <value>
                    <fullName>Inactive - Client Discontinued Support</fullName>
                    <color>#FF0000</color>
                    <label>Inactive - Client Discontinued Support</label>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                    <color>#FF0000</color>
                    <label>Pending Renewal</label>
                </value>
                <value>
                    <fullName>Renewal Due</fullName>
                    <color>#009900</color>
                    <label>Renewal Due</label>
                </value>
                <value>
                    <fullName>No HW Support, Software Only</fullName>
                    <color>#009900</color>
                    <label>No HW Support, Software Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Contract type designates a billing category for the service contract for Pro Forma invoicing</description>
        <inlineHelpText>Designates type of product covered by this contract</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>911</fullName>
                    <color>#F3D904</color>
                    <label>911</label>
                </value>
                <value>
                    <fullName>Advanced Reporting Module</fullName>
                </value>
                <value>
                    <fullName>Advanced Reporting Module Hosted</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                    <color>#E27001</color>
                    <label>APS</label>
                </value>
                <value>
                    <fullName>AVeL</fullName>
                    <color>#0B6FCE</color>
                    <label>AVeL</label>
                </value>
                <value>
                    <fullName>CAD 2000</fullName>
                    <color>#33FFFF</color>
                    <label>CAD 2000</label>
                </value>
                <value>
                    <fullName>CDP IMC</fullName>
                </value>
                <value>
                    <fullName>CDP Inform</fullName>
                </value>
                <value>
                    <fullName>CDP Zuercher</fullName>
                </value>
                <value>
                    <fullName>Copperfire</fullName>
                    <color>#33FFFF</color>
                    <label>Copperfire</label>
                </value>
                <value>
                    <fullName>CrimeMapping Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard</fullName>
                </value>
                <value>
                    <fullName>CrimeView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>CrimeView Desktop</fullName>
                </value>
                <value>
                    <fullName>DN CAD/Mobile</fullName>
                    <color>#33FFFF</color>
                    <label>DN CAD/Mobile</label>
                </value>
                <value>
                    <fullName>Emergin</fullName>
                    <color>#E27001</color>
                    <label>Emergin</label>
                </value>
                <value>
                    <fullName>ETI</fullName>
                </value>
                <value>
                    <fullName>ETI 911</fullName>
                </value>
                <value>
                    <fullName>ETI 911 ANI Link</fullName>
                </value>
                <value>
                    <fullName>ETI 911 Hardware</fullName>
                </value>
                <value>
                    <fullName>ETI Hardware</fullName>
                </value>
                <value>
                    <fullName>FACTS</fullName>
                    <color>#33FFFF</color>
                    <label>FACTS</label>
                </value>
                <value>
                    <fullName>FDC</fullName>
                    <color>#0B6FCE</color>
                    <label>FDC</label>
                </value>
                <value>
                    <fullName>Field Ops</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard</fullName>
                </value>
                <value>
                    <fullName>FireView Dashboard Hosted</fullName>
                </value>
                <value>
                    <fullName>FireView Desktop</fullName>
                </value>
                <value>
                    <fullName>GEO Comm</fullName>
                    <color>#E27001</color>
                    <label>GEO Comm</label>
                </value>
                <value>
                    <fullName>GIS Maintenance</fullName>
                </value>
                <value>
                    <fullName>Go To Assist</fullName>
                    <color>#E27001</color>
                    <label>Go To Assist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Support_Ticket_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These settings allow configuration of automated steps on support tickets - drives the landing page and ticket record types for any new implementations or edits to existing product families.</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Match this field to the contract type the ticket is created from</description>
        <label>Contract Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landing_Page__c</fullName>
        <description>Use this setting to determine the landing page for the for the record type</description>
        <label>Landing Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Support Ticket Settings</label>
</CustomObject>

src/classes/CreateServiceTicketController.cls
public class CreateServiceTicketController {
	
    public List<PortalContract> PortalContracts {get;set;}
    public User CurrentUser {get; set;}
    public Contact CurrentContact {get; set;}
    
    public CreateServiceTicketController(){
    	setCurrentUser();
    	setCurrentContact();
    	setPortalContracts();
    }
    
    
    private void setCurrentUser(){

    	User u = new User(Id=UserInfo.getUserId());
    	CurrentUser = [Select Id,Name,Email,Phone,Title,ContactId,Profile.Name From User Where Id = :u.Id limit 1];
    }
    private void setCurrentContact(){

    	//Contact c = new Contact(Id=CurrentUser.ContactId);
    	CurrentContact = [Select Id, AccountId From Contact Where Id = :CurrentUser.ContactId limit 1];
    	
    }
    
    private void setPortalContracts(){

    	list <ServiceContract> serviceContracts = new list <ServiceContract>();
    	serviceContracts = [Select s.Id,s.Status, s.Contract_Status_WMP__c,s.AccountId, s.name, s.Contract_Type__c From ServiceContract s 
    						Where Contract_Status_WMP__c IN ('Active','Installed Not Live','Renewal Due','No HW Support, Software Only') AND AccountId =:CurrentContact.AccountId];

    	list<PortalContract>pContracts = new list<PortalContract>();
    	for(ServiceContract sc: serviceContracts){
    		
        	PortalContract pc = new PortalContract();
            pc.Name = sc.name == null?'':sc.name; 
            pc.contractType = sc.Contract_Type__c == null?'':sc.Contract_Type__c;
            pc.Id = sc.Id;
            pc.setLandingPage(sc.Contract_Type__c == null?'':sc.Contract_Type__c);
            pc.Status = sc.Status;
            pc.ContractStatus = sc.Contract_Status_WMP__c;
            pContracts.add(pc);                        	
        }
        PortalContracts = pContracts;
    }
    
	
	 class PortalContract{
    	public string Name {get; set;}
    	public string ContractType {get; set;}
    	public string Id {get; set;}
    	public string LandingPage {get; set;}
    	public string Status {get; set;}
    	public string ContractStatus {get; set;}
    	
    	
    	public void setLandingPage(string ct){
    		map<string,string> landingPages = new map<string,string>();
    		
    		for(Support_Ticket_Settings__c rt : Support_Ticket_Settings__c.getAll().values()){
    			LandingPages.put(rt.Contract_Type__c,rt.Landing_Page__c);
			}
			
			if(!landingPages.containsKey(ct)){
				LandingPage = landingPages.get('Default');
			}
			else{
				LandingPage = landingPages.get(ct);
			}
		}
		   
    }
    
}